### ISSUE TITLE
[BUG] The in-game chat is only in English in the Community version

### ISSUE THREAD

**Issue by ArmorKeik** [CriticalFlaw/TF2HUD.Fixes#101]
**Issue**
The chat style in the Community version is only in English.
The Filters option and "Say:" (see images) were not translated into other languages.
The only thing that is translated is the menu that appears when you right-click on the chat.

**Specifications**
Branch: Community.
Operating system: Windows 10.
Language: Spanish (I've also tried German and got the same results, it seems to happen with all languages.)
Screen resolution: 1360x768

**Screenshots**

![20221201145231_1](https://user-images.githubusercontent.com/87909542/205126997-76a6c1d2-e92d-40cd-b229-2a523c352ebc.jpg)
![20221201145633_1](https://user-images.githubusercontent.com/87909542/205127006-ecb87d9c-00d1-41d4-bdbc-d3617f114c43.jpg)

**Comment by CriticalFlaw** [comment]
Fixed in f06cbc2265602d0211120fc753c5876193e8c026. Thanks
