### ISSUE TITLE
[BUG] [COMMUNITY] Bread Bite Killicon is misalligned.

### ISSUE THREAD

**Issue by BreavyTF2** [CriticalFlaw/TF2HUD.Fixes#102]
The kill icon for the bread bite misaligned in game, it can be fixed by changing
`		"bread_bite"
		{
				"dfile"	"vgui/logos/ImprovedKillIcons/d2"
				"dnegfile"	"vgui/logos/ImprovedKillIcons/dneg2"
				"x"		"129"
				"y"		"133"
				"width"		"96"
				"height"	"32"
		}
`
to
`		"bread_bite"
		{
				"dfile"	"vgui/logos/ImprovedKillIcons/d2"
				"dnegfile"	"vgui/logos/ImprovedKillIcons/dneg2"
				"x"		"129"
				"y"		"133"
				"width"		"79"
				"height"	"26"
		}
`

**Comment by CriticalFlaw** [comment]
Can you post a screenshot comparison please?

**Comment by BreavyTF2** [comment]
![image](https://user-images.githubusercontent.com/37123222/206090543-96700cb4-a137-4d16-af0d-09f93fd43a32.png)
![image](https://user-images.githubusercontent.com/37123222/206090546-7acfb43e-9831-4b10-8f5c-282efadfb7ba.png)

**Comment by CriticalFlaw** [comment]
Thank you for the report and fix.
