### ISSUE TITLE
[BUG] `ChargeLabel` in `HudDemomanPipes.res` cuts off by screen edges when a shield is equipped.

### ISSUE THREAD

**Issue by qkeitoe** [CriticalFlaw/TF2HUD.Fixes#105]
**Issue**

`ChargeLabel` in `HudDemomanPipes.res` cuts off by screen edges when a shield is equipped.

I believe it was caused by changes in 9f341ecfcb83b06775f14ee12eabe13e1caf16c0.

**Specifications**

BRANCH: community
OS: Windows 10
LANG: Eng
RESOLUTION: 1920x1080

**Screenshots**

![2022-12-26_06-48-37](https://user-images.githubusercontent.com/66339491/209497499-75783c80-6ecf-4c42-b2f0-d5592823a057.png)

**Comment by ArmorKeik** [comment]
I leave this screenshot here to show that the bug you are reporting is not an isolated case.

**Specifications**

Branch: Community
Operating system: Windows 10
Language: Spanish
Screen resolution: 1360x768

**Screenshots**

![20221227161507_1](https://user-images.githubusercontent.com/87909542/209717035-19f277f2-077e-40d5-b051-bf9136823b33.jpg)

**Comment by CriticalFlaw** [comment]
Fixed in d38f67574325c68afdb7fe329e11628a8f0ea082
