### ISSUE TITLE
[BUG] Killstreak counter and Engineer crits counter overlapping with other elements

### ISSUE THREAD

**Issue by aevidd** [CriticalFlaw/TF2HUD.Fixes#106]
![Untitled](https://user-images.githubusercontent.com/117964445/209665906-3d2fb5e9-faf1-4bd8-9944-6fc97bd24b0e.png)
![Untitled 1](https://user-images.githubusercontent.com/117964445/209665914-30cc706d-fa67-4784-af7a-199279636b53.png)

**Comment by CriticalFlaw** [comment]
Fixed in d38f67574325c68afdb7fe329e11628a8f0ea082. Thank you for reporting!
