### ISSUE TITLE
[REQUEST] add "inventory_image_type"  "1" to resource/ui/econ/itemmodelpanel.res

### ISSUE THREAD

**Issue by Whurrhurr** [CriticalFlaw/TF2HUD.Fixes#107]
**Is your feature request related to a problem? Please describe.**
achieves the same effect as adding "inventory_image_type"  "1" to say, hudweaponselection's itemmodelpanels (the panels on the right of your hud if you have weapon quick switch disabled, or if you press 0, but that file isn't touched by this mod, so the icons show up blurry)

examples:
hudupgradepanel
![image](https://user-images.githubusercontent.com/33162051/220391784-8ccd6ac8-7b3f-4948-9810-c7b785fd538c.png)

hudweaponselection
![image](https://user-images.githubusercontent.com/33162051/220392227-35bc8d75-f4cf-4385-bfad-74580dd568dd.png)

(i don't know what res file this is, but i do know that the icons are blurry even with the mod installed)
![image](https://user-images.githubusercontent.com/33162051/220395257-f97add09-12d6-4ecd-9b5a-8a7565f4d31c.png)

all of these are not touched by this mod, and they both have crispy clear weapon icons now. all screenshots were taken without the mod installed.

if you want to see this for yourself, here's the file.
[itemmodelpanel.zip](https://github.com/CriticalFlaw/TF2HUD.Fixes/files/10795209/itemmodelpanel.zip)

**Comment by Whurrhurr** [comment]
oh, you can get rid of the second instance of "inventory_image_type" "1" that i put in contained_item_panel, because at the time i didn't realize UI elements that use an itemmodelpanel would inherit all settings from the itemmodelpanel in MainContentsContainer (anything else set in other itemmodelpanels overrides the setting put in, for example, if i had an itemmodelpanel in hudweaponselection with an fov of 75, those model panels for that specific hud element would use 75 fov, but every other model panel, unless specified will use the default fov setting in MainContentsContainer, which is 54)

**Comment by CriticalFlaw** [comment]
That's a great find. I've pushed the change in 41da04b37e2b9c4fe10a3668e61a0f4e52ded185. Could you verify when you get the chance? It looked good from my testing.

Also, you should publish this to the Steam Workshop. This is a much better way to implement this change then adding dozens of `inventory_image_type` to files.

**Comment by CriticalFlaw** [comment]
I've kept instances of `inventory_image_type` that already exist in the default HUD and only removed ones added for this mod. Just to keep things as close to the default as possible.

**Comment by Whurrhurr** [comment]
> That's a great find. I've pushed the change in [41da04b](https://github.com/CriticalFlaw/TF2HUD.Fixes/commit/41da04b37e2b9c4fe10a3668e61a0f4e52ded185). Could you verify when you get the chance? It looked good from my testing.


can confirm it works, the only problem i've run into is that certain backpack icons do not get dimmed when you cannot select them (because they conflict with something else you have equipped) and the cause seems to be that those icons' _large vmts lack "$vertexcolor" 1

**Comment by CriticalFlaw** [comment]
It shouldn't be a problem for Valve to add then if they decide to add this change into the game officially. I think for the scope of this mod this is sufficient. If you do end up making a Workshop submission of this, it'd be good to include a README note to Valve about that issue though.

**Comment by valeriedesumo** [comment]
I don't feel that the "HQ" backpack images are a direct objective upgrade, and so would be better suited for the extras folder. This change makes the items very aliased, and this can be seen in the attached comparison images. Details like the gears on refined metal, thin lines on earbuds and seal mask, and any diagonal like on direct hit all show strong aliasing. Additionally, some details look (subjectively) better on "LQ", such as the squad surplus looking more like a printed ticket, and the quackenbirdt's lines around the duck becoming more uniform. However, some details are better with the change like the fortified compound's bowstring becoming much more visible. 

With "inventory_image_type" "1"
![hq](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/17819819/44c58103-7639-439b-a66a-8ba73569bf98)
Without "inventory_image_type" "1"
![lq](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/17819819/0e7634bb-25c5-484b-8a2e-4957b1ab596f)
