### ISSUE TITLE
[BUG] Incorrectly positioned news blog

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/TF2HUD.Fixes#108]
**Specifications**
* branch - community
* operating system - Windows and Linux
* language - english
* screen resolution - 1920x1080

**Screenshots**
![1](https://user-images.githubusercontent.com/117596825/222871654-bbd39592-569d-4ef2-a0ac-6eda1bc1206f.png)

**Comment by CriticalFlaw** [comment]
Fixed in be5a8e249a5aa0887268ee2a674db0553801cadd.

After downloading the latest version, copy the contents of `.extras` folder into the root HUD directory. Alternatively, download from the `complete` branch: https://github.com/CriticalFlaw/TF2HUD.Fixes/archive/refs/heads/complete.zip
