### ISSUE TITLE
[REQUEST] Problem with files and folders with uppercase names in linux

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/TF2HUD.Fixes#109]
Please read this: https://github.com/JarateKing/TF2-Hud-Reference/blob/master/1-APPENDIX/LinuxSupport.md

Remove capital letters from the names of all files and folders, this will not affect the work of hud in windows, but will make life easier for linux users

Github:
TF2HUD.Fixes-main (Remove the uppercase letters from the name of this folder.)
TF2HUD.Fixes-main/materials/vgui/maps/menu_thumb_Missing.vmt
TF2HUD.Fixes-main/.extras/resourse/TF2Crosshairs.png
TF2HUD.Fixes-main/.extras/resourse/TF2Crosshairs.ttf

Github (releases):
tf2hud-fixes/tf2hud/materials/vgui/maps/menu_thumb_Missing.vmt
tf2hud-fixes/tf2hud/.extras/resourse/TF2Crosshairs.png
tf2hud-fixes/tf2hud/.extras/resourse/TF2Crosshairs.ttf

Gamebanana:
tf2hud-fixes_0a836/tf2hud/materials/vgui/maps/menu_thumb_Missing.vmt
tf2hud-fixes_0a836/tf2hud/.extras/resource/TF2Crosshairs.png
tf2hud-fixes_0a836/tf2hud/.extras/resource/TF2Crosshairs.ttf

**Comment by CriticalFlaw** [comment]
Updated in 27f884a8c6e005264502fe9fb55697ab5e015b0c and 6ca8516f0408b40fd62985f84ce6b74e6c73e82f. Thanks!

**Comment by CriticalFlaw** [comment]
That would require renaming the entire GitHub repository and subsequent links.
