### ISSUE TITLE
ItemsLabel not using a scaling font in lower resolutions

### ISSUE THREAD

**Issue by ghost** [CriticalFlaw/TF2HUD.Fixes#11]
Only happens in lower resolutions I believe, currently using 4:3 1024x768. Maybe make text smaller?
![image](https://user-images.githubusercontent.com/34733116/99433621-972ce380-28c2-11eb-8638-64f1796a9914.png)
![image](https://user-images.githubusercontent.com/34733116/99433630-9a27d400-28c2-11eb-9779-118ac52f99fb.png)
![image](https://user-images.githubusercontent.com/34733116/99433634-9bf19780-28c2-11eb-97c4-e6f47942b544.png)

**Comment by CriticalFlaw** [comment]
This could potentially be fixed by having **ItemsLabel** in `resource/ui/charinfoloadoutsubpanel.res` use a scaling font when in lower resolutions. But I'm not yet sure if that's possible and if so, how to do it.
