### ISSUE TITLE
[REQUEST] Remove unnecessary folders

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/TF2HUD.Fixes#110]
So that after unzipping you can immediately put the "tf2hud" folder into the custom folder, instead of going to the first folder first and only then putting the "tf2hud" folder into the custom folder.

If you do not follow the above inconvenient steps, the hud will not work

Github (releases):
tf2hud-fixes/tf2hud

Gamebanana:
tf2hud-fixes_0a836/tf2hud

**Comment by CriticalFlaw** [comment]
I don't quite understand the ask. When you download the hud, you extract the contents (`tf2hud`) into your `tf/custom` folder. That's the only way for the HUD to work.

When you extract, you can do so **without** creating an extra folder. In the example below using 7-Zip, by default it will create a separate folder called tf2hud-fixes with tf2hud inside it. If I remove `tf2hud-fixes` it will extract just `tf2hud` into my Downloads folder.

![image](https://user-images.githubusercontent.com/6818236/222969284-120ef32c-78e6-46a3-94be-4922f01d217e.png)

**Comment by CriticalFlaw** [comment]
You can just do it in one step and have it extract directly into the `tf/custom` folder, without needing to enter into or move the folder yourself.

![image](https://user-images.githubusercontent.com/6818236/222972103-5a9beb55-cd36-4ecb-a669-642cce8445c6.png)

![image](https://user-images.githubusercontent.com/6818236/222972110-cfeed7cc-4d24-4853-9a47-4cd40ca91371.png)
