### ISSUE TITLE
[REQUEST] Add HD TF2 Menu Logo

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/TF2HUD.Fixes#115]
https://gamebanana.com/mods/27061
Wait, you misunderstood me!

It is different from the community branch. The HD version of the logo was taken from Steam and you can see that it's the same original but in high quality (not upscaled by AI and not recreated by the artist)

Original:
![original](https://user-images.githubusercontent.com/117596825/222970840-47481e3d-23be-4f4e-9ed5-73df08e6c6a3.png)
HD mod:
![no](https://user-images.githubusercontent.com/117596825/222970843-952d5c86-8a14-4f7e-aef2-a8e0417d08f2.png)
Community Branch:
![inhud](https://user-images.githubusercontent.com/117596825/222970844-3cc5b41b-0bd5-4be6-b30e-c75aaa3003e7.png)

**Comment by CriticalFlaw** [comment]
Hi. You can just comment on the original ticket, no need to create duplicates. 

There's no more community branch as extra options are in the `.extras` folder. I could replace it but I think it may be best to keep art-asset changes separate from the rest of the HUD and leave it to the individual user to decide and install whichever variant they prefer.
