### ISSUE TITLE
[BUG] Health text color is incorrect when using extras.

### ISSUE THREAD

**Issue by kittenchilly** [CriticalFlaw/TF2HUD.Fixes#116]
**Issue**
The text that displays your HP in the cross is white, making it really hard to see.
It was not like this before a recent update.

**Specifications**
I am on main and am using the extras.

**Screenshots**
![20230307182058_1](https://user-images.githubusercontent.com/23617175/223587458-9916274b-781c-4957-8a8f-6b9e60e602ef.jpg)

**Comment by kittenchilly** [comment]
Update: Somehow I got it to be yellow?
![20230307183102_1](https://user-images.githubusercontent.com/23617175/223587919-6c6e1733-07bc-4a34-a8a0-6ada42cd9d56.jpg)

**Comment by CriticalFlaw** [comment]
May be an animations conflict with the extras. Will check it out today.

**Comment by CriticalFlaw** [comment]
Fixed in 55a648a2669c409997e65a6138891df051f0d488. The animations targetID health value was being applied to the player health in your screenshot.
