### ISSUE TITLE
[BUG] The text "queued for ..." overlaps the name of the map

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/TF2HUD.Fixes#121]
**Specifications**
Operating system - Linux
Resolution - 1920x1080

**Screenshots**
![esrjjjjj](https://user-images.githubusercontent.com/117596825/224650515-a2484bb4-8705-4227-ba85-edf27bb26729.jpg)

**Comment by CriticalFlaw** [comment]
Good catch. Will correct that tonight

**Comment by CriticalFlaw** [comment]
Fixed in 7aa7a8ec9a39608027a420aecfa7960757e36774. Thank you for reporting.

![20230314192227_1](https://user-images.githubusercontent.com/6818236/225163714-8bbcc2ed-73f3-475e-90d2-79c77bd0195c.jpg)
