### ISSUE TITLE
[BUG] Engineer sentrygun build status overlaps the description of the mouse buttons

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/TF2HUD.Fixes#122]
**Specifications**
* Operating system - Linux
* Resolution - 1920x1080

**Screenshots**
![pvherjh](https://user-images.githubusercontent.com/117596825/225551764-bcc4e891-7b3f-4328-bccb-8166dba902ce.jpg)

**Comment by CriticalFlaw** [comment]
Fixed in 5444cd3d370218eeef9247f565522e68c3ecf37b. Thank you for reporting.

**Comment by CriticalFlaw** [comment]
Reopening to fix the respawn timer overlap.
![image](https://user-images.githubusercontent.com/6818236/226779733-32d3dbab-a5da-4a9e-b5fd-00f6c358f375.png)

**Comment by CriticalFlaw** [comment]
Let's try this again.
![20230321214352_1](https://user-images.githubusercontent.com/6818236/226780199-575eb999-ee2d-490f-bbaa-fb233b0ad08a.jpg)
