### ISSUE TITLE
[BUG] No description of the space button

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/TF2HUD.Fixes#123]
**Issue**
I noticed that in your screenshot there is a description of the spacebar button, but I don't have it for some reason.

**Specifications**
Operating system - Fedora Linux 37 (Workstation Edition)
Resolution - 1920x1080

**Screenshots**
![hhhhdsaf](https://user-images.githubusercontent.com/117596825/225881734-a1e05223-7ec0-4c99-ae49-44a2bb7b2e9a.jpg)

**Comment by CriticalFlaw** [comment]
Try switching between free cam and following a player. I think it only appears in certain scenarios and not all the time.
