### ISSUE TITLE
[BUG] The text "waiting for players" slightly overlaps the team panel

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/TF2HUD.Fixes#124]
**Specifications**
Operating system - Linux
Resolution - 1920x1080

**Screenshots**
![gggdsdvvv](https://user-images.githubusercontent.com/117596825/225930738-c67763fc-daea-4b0c-9d9b-2781a94dea57.jpg)

**Comment by CriticalFlaw** [comment]
Don't think there's much to change here because then it would be too low.
