### ISSUE TITLE
[BUG] The "On the bright side" window overlaps the ID of the main target

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/TF2HUD.Fixes#125]
**Specifications**
Operating system - Linux
Resolution - 1920x1080

**Screenshots**
![aahhhg](https://user-images.githubusercontent.com/117596825/226083352-bce168b5-28a1-4e23-819e-6191a8d9b431.jpg)

**Comment by CriticalFlaw** [comment]
This is fine. There's not much space where else it could reside.
