### ISSUE TITLE
[BUG] The current disguise panel overlaps the spell counter

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/TF2HUD.Fixes#126]
**Specifications**
* Operating system -  Fedora Linux 37 (Workstation Edition)
* Resolution - 1920x1080

**Screenshots**
![kkj](https://user-images.githubusercontent.com/117596825/226148189-ee559df7-5e4a-467e-a8b1-eeda005545cc.jpg)

**Comment by CriticalFlaw** [comment]
This is consistent with the disguise panel overlapping the player panel, killstreak and now the spell panel. No change needed here.
