### ISSUE TITLE
[BUG] The upper part of the ammo numbers is cut off

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/TF2HUD.Fixes#127]
**Issue**
It happens when using weapons without a clip

**Specifications**
* Minimal hud mode is used
* Operating system - Fedora Linux 37 (Workstation Edition)
* Resolution - 1920x1080

**Screenshots**
![200](https://user-images.githubusercontent.com/117596825/226151930-2eb5e103-cf64-4eef-854a-60cbcad2cd8c.jpg)

**Comment by CriticalFlaw** [comment]
Fixed in b82e9c2705fcc5ff8394deb87202422fdf36edad. For now this is only in the `extras` option. Thanks for reporting.

![20230321204452_1](https://user-images.githubusercontent.com/6818236/226773192-4307825a-4ae4-4e22-90ee-2dd8e62fca30.jpg)
