### ISSUE TITLE
[BUG] The vaccinator icon overlaps the medic ubercharge info

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/TF2HUD.Fixes#128]
**Specifications**
* Minimal hud mode is used
* Operating system - Fedora Linux 37 (Workstation Edition)
* Resolution - 1920x1080

**Screenshots**
![bnf](https://user-images.githubusercontent.com/117596825/226181346-d7f200c2-25ac-487f-b2a5-02cd182e7e9f.jpg)

**Comment by CriticalFlaw** [comment]
According to the default HUD file `resource/ui/hudmediccharge.res` - the icon is not supposed to be visible when in minmode. For some reason this condition is not being respected. Best to report this to the source 1 tracker to have them fix it in the core properly

![image](https://user-images.githubusercontent.com/6818236/226774593-e7c1c4ca-c4d8-4c41-837e-e8142792a1f1.png)

**Comment by CriticalFlaw** [comment]
The compromise can be to make the icon smaller when in minmode. But it then seems like a customization ideal for the `extras` folder.

![image](https://user-images.githubusercontent.com/6818236/226774762-a0f0570c-c211-47d7-be9c-24cd1026df43.png)

![image](https://user-images.githubusercontent.com/6818236/226774797-8d4c9665-9189-48f9-bb57-7c591d6c5dda.png)
