### ISSUE TITLE
[BUG] "Respawn in: ..." overlaps the description of the buttons

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/TF2HUD.Fixes#129]
**Specifications**
* Operating system - Fedora Linux 37 (Workstation Edition)
* Resolution - 1920x1080

**Screenshots**
![isss](https://user-images.githubusercontent.com/117596825/226778075-05bba4e4-cb72-4822-afb8-ff82988da8fe.jpg)

**Comment by CriticalFlaw** [comment]
You can just reopen the old ticket because it's related to that.

**Comment by CriticalFlaw** [comment]
Closing to be fixed in https://github.com/CriticalFlaw/TF2HUD.Fixes/issues/122
