### ISSUE TITLE
[BUG] Matchmaking dashboard overlaps the match summary scoreboard

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/TF2HUD.Fixes#131]
https://github.com/ValveSoftware/Source-1-Games/issues/4802
**Specifications**
Operating system - Fedora Linux 37 (Workstation Edition)
Resolution - 1920x1080

**Screenshots**
![1](https://user-images.githubusercontent.com/117596825/221506975-ffccd507-9247-413e-b6c1-f86c8676e08b.png)

**Comment by CriticalFlaw** [comment]
Fixed in https://github.com/CriticalFlaw/TF2HUD.Fixes/pull/162 by @impale1
