### ISSUE TITLE
[BUG] MVM Minimal HUD Wave Number Fix No Longer Works

### ISSUE THREAD

**Issue by bagfri3s** [CriticalFlaw/TF2HUD.Fixes#132]
**Issue**
Enabling minimal HUD in Mann vs Machine no longer displays the wave numbers (wave x/x) and sometimes a gray box appears over the wave progress bar

**Specifications**
mastercomfig "high" preset
Launch options: -high -threads 24 -borderless -windowed -noborder -novid -nojoy -nosteamcontroller -nohltv -particles 1 -precachefontchars -noquicktime

**Screenshots**
Minimal HUD on:
![20230401090948_1](https://user-images.githubusercontent.com/22801658/229302369-3f755a1e-7676-460d-b51f-bb4d971dd012.jpg)

Minimal HUD off:
![20230401091006_1](https://user-images.githubusercontent.com/22801658/229302391-4c35dae9-0eac-4ef0-8e5e-085584ad15cd.jpg)

**Comment by Desenrrollado** [comment]
I'm similarly having this issue. It would be nice if this could be fixed.
![image](https://user-images.githubusercontent.com/92115460/229302460-e7064a1b-de2e-4c20-9f8d-adfb1b0c6e6a.png)

**Comment by CriticalFlaw** [comment]
Looks correct on the GitHub main and complete branches. Where did you download this version from?

![20230401133540_1](https://user-images.githubusercontent.com/6818236/229306038-b34212e2-652c-4aac-a6f0-57330e7aaafa.jpg)

**Comment by bagfri3s** [comment]
I downloaded the files from the GitHub page at:
https://github.com/CriticalFlaw/TF2HUD.Fixes

**Comment by bagfri3s** [comment]
> It looks like you installed the hud incorrectly. Inside the tf2hud-fixes and workshop-only folders is the tf2hud folder, which should be moved to the custom folder.
> 
> Or, if you are a linux user and downloaded the main branch, you need to remove all capital letters from the folder name

Ah I see that was the problem. Thanks for the info
