### ISSUE TITLE
[REQUEST] Bring back button shortcuts

### ISSUE THREAD

**Issue by Ashetf2** [CriticalFlaw/TF2HUD.Fixes#133]
**Is your feature request related to a problem? Please describe.**
The HUD used to have button shortcuts but they were removed in a recent update

**Additional context**
Button shortcuts for: Back and Next buttons, View loadout button in the class selection screen, etc

**Comment by CriticalFlaw** [comment]
Navigation buttons are already included in the `extras` folder - just copy the folder contents into the root HUD directory. Alternatively download the HUD from the `complete` branch - https://github.com/CriticalFlaw/TF2HUD.Fixes/tree/complete

**Comment by Ashetf2** [comment]
Mmm I did exactly that and there are no shortcuts. Only A and D works in the backpack.

**Comment by Ashetf2** [comment]
Also, the latest release doesn't have the extras folder for some reason
