### ISSUE TITLE
[BUG] HD item images broke mannpower images

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/TF2HUD.Fixes#135]
**Issue**
When a player with a powerup kills you, you will be shown what his powerup is
Due to newly added hd images a purple texture will be displayed instead of powerup
Removing `itemmodelpanel.res` fixes this

**Specifications**
Operating system - Fedora Linux 37 (Workstation Edition)
Resolution - 1920x1080

**Comment by CriticalFlaw** [comment]
It seems like something that could be fixed on the game code side to accomodate this change rather than reverting all together for majority of players who don't play Mannpower.

**Comment by CriticalFlaw** [comment]
It's a valid issue, I wonder if there's a fix for it in the HUD files other than just removing the change from itemmodelpanel altogether. @Whurrhurr thoughts?

**Comment by Whurrhurr** [comment]
currently seeing how mannpower powerups are done in the item inspection panel, will post again when i get some results

**Comment by Whurrhurr** [comment]
ok so according to items_game.txt, the powerups use "effects/powerup_[powerup_name]_hud" as their "backpack icon" so making _large variants of those would fix this, but it would also (probably) be incompatible on valve servers (and any community server that does not allow materials/effects in their sv_pure whitelists) so it's entirely up to you if you want to revert the changes made to itemmodelpanel.

**Comment by CriticalFlaw** [comment]
@rabscootle apologies for the ping. Do you have any thoughts on this?

**Comment by rabscootle** [comment]
...not entirely sure. Are the _large files in post below 512x512 resolution?

> tried making _large versions of the icons, was greeted with this ![image](https://user-images.githubusercontent.com/33162051/231094750-221617ed-0d13-40f5-b8a5-e068b2dd760b.png) don't think we have much of a choice here.

**Comment by Whurrhurr** [comment]
> ...not entirely sure. Are the _large files in post below 512x512 resolution? That would be my first guess.
> 
> Probably can't be 100% fixed without Valve adding proper _large thumbnails no copies exist in game files (game schema currently calls for particle sprites for the backpack icons)

those were not 512x512, as there was no _large.vtf versions of the sprites they use for backpack icons, so i just made the vmts point to the one the normal-sized ones use. i was just gonna wait for the summer update to come out and see if they implement your mannpower backpack icon thing in, but the "force _large backpack icons" change can be made an extra with a note that it breaks mannpower powerups in the "[Playername] is carrying" panel

**Comment by rabscootle** [comment]
Yeah this can't be fixed without intervention from Valve, sadly. If you try fixing this on your end it involves editing the particle that's used in normal gameplay.

**Comment by CriticalFlaw** [comment]
Marking this as won't do because it is engine-related.
