### ISSUE TITLE
[REQUEST] Expland the player list on the pre-match screen

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/TF2HUD.Fixes#137]
https://github.com/ValveSoftware/Source-1-Games/issues/4898
**Specifications**
Operating system - Fedora Linux 37 (Workstation Edition)
Resolution - 1920x1080

**Screenshots**
![333](https://user-images.githubusercontent.com/117596825/231556248-fbe87d35-0758-4ea3-854f-c271fb388e49.png)

**Comment by CriticalFlaw** [comment]
That's not a bug. This is a request, which should go on the official source 1 tracker

**Comment by CriticalFlaw** [comment]
Can you post a PR with this change please?

**Comment by CriticalFlaw** [comment]
Added in https://github.com/CriticalFlaw/TF2HUD.Fixes/pull/160
