### ISSUE TITLE
[BUG] Briefcase overlaps the timer/skull in mannpower

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/TF2HUD.Fixes#139]
**Specifications**
Operating system - Fedora Linux 37 (Workstation Edition)
Resolution - 1920x1080

**Screenshots**
![1](https://user-images.githubusercontent.com/117596825/232335870-9341bd07-d78b-47b5-ad18-daff3fea0e9c.png)
![2](https://user-images.githubusercontent.com/117596825/232335872-1cbfde99-f674-445b-b583-1348c54b63a6.png)
![skull](https://user-images.githubusercontent.com/117596825/233847194-73cec9f3-6275-4dca-a102-992d036e3452.png)

**Comment by CriticalFlaw** [comment]
Fixed in 7b8fef76692660e2e7ddca6f792458795c414c07. Thanks
