### ISSUE TITLE
[BUG] Black Bars/Glitched Items under decorated items on spectated players in 1440p resolution

### ISSUE THREAD

**Issue by Presto06** [CriticalFlaw/TF2HUD.Fixes#140]
**Issue**
Black Bars/Glitched Items under decorated items on spectated players in 1440p resolution

Is an issue with the default hud aswell however seems to be fixable as showcased in other huds such as FlawHUD or BudHud

On the default hud the issue seems to be also present in the backpack but it appears to have already been fixed by these hud fixes

**Specifications**
OS: Windows 11 
Resolution: 2560x1440

**Screenshots**
Black Bars:
![image](https://user-images.githubusercontent.com/123919000/233243400-6d14c6ce-b6d2-44e6-8296-760f6663ee85.png)

Glitched Items (correlates with items in your inventory):
![image](https://user-images.githubusercontent.com/123919000/233243459-1b333b2e-34a7-4a9f-add7-8510cc60e40c.png)

**Comment by CriticalFlaw** [comment]
This fix is already ported from flawhud, though it's not perfect as there are some edge cases that are still not covered. Preferably Valve would just fix it on their side. Here are screenshots for comparison

Default HUD
![before](https://user-images.githubusercontent.com/6818236/235043531-83902642-710b-474d-9193-cdc3fa1004c3.png)

HUD Fixes (main and complete branches)
![after](https://user-images.githubusercontent.com/6818236/235043542-6fb4e120-2ef1-49df-a60f-200b4923200c.png)
