### ISSUE TITLE
[REQUEST] Make target ids more visible

### ISSUE THREAD

**Issue by Presto06** [CriticalFlaw/TF2HUD.Fixes#141]
**Is your feature request related to a problem? Please describe.**

Right now the target ids for when you hover over a player or when you heal as a medic or being healed by one are really hard to see under certain colors especially the white text *screenshot below* so my suggestion is to perhaps add a shadow behind the white text like the damage numbers and maybe make the background a bit less transparent or darker or atleast something to make them more visible

**Additional context**

![image](https://user-images.githubusercontent.com/123919000/233517977-2d968903-df7a-4702-b72a-4583a83d76b3.png)

![image](https://user-images.githubusercontent.com/123919000/233518011-a52eb6f2-0fda-4371-be53-97aa6ee5c1d0.png)

**Comment by CriticalFlaw** [comment]
You'll need to adjust the `TargetID Alpha` value in Advanced Settings. See screenshots below:

![20230528180043_1](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/6818236/0e752fe8-7f4c-4fa1-8fcd-6c41cd763cb4)

**Alpha at 255**
![20230528180056_1](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/6818236/275aa4b8-e931-4851-9abd-373dc3ab9e06)

**Alpha at ~120**
![20230528180124_1](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/6818236/27a02f1e-374b-4af6-ab2c-83ba0c5a9613)
