### ISSUE TITLE
[BUG] Certain health values cut off on deathcam

### ISSUE THREAD

**Issue by Presto06** [CriticalFlaw/TF2HUD.Fixes#142]
**Issue**
Certain health values cut off on deathcam, appears to happen on the number 300 and potentially some others
(Possibly a issue with my resolution)

**Specifications**
Resolution: 2560x1440
OS: Windows 11

**Screenshots**
![image](https://user-images.githubusercontent.com/123919000/233829224-6decf014-469a-4b2e-abf0-8228c5e36f89.png)

**Comment by CriticalFlaw** [comment]
Fixed in a13eba420a7221c3a99c8ae3c9c9d2152783cb53. Thanks
![20230427223714_1](https://user-images.githubusercontent.com/6818236/235041207-4247df42-4e5d-47af-be82-b06e56f0ce65.jpg)
