### ISSUE TITLE
[BUG] Inconsistency between the 3D player model and the 2D image

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/TF2HUD.Fixes#144]
**Issue**
While the 3D model does not cover the bottom white line, the 2D image completely covers it
Same problem in the scoreboard
I don't know exactly which one is right, but in my opinion, the 3D model is wrong here.

**Specifications**
Operating system - Fedora Linux 37 (Workstation Edition)
Resolution - 1920x1080

**Screenshots**
![2](https://user-images.githubusercontent.com/117596825/235343768-98a835a1-838e-4c08-b9e6-864f7d248238.png)
![1](https://user-images.githubusercontent.com/117596825/235343765-160c4794-65b5-4124-99b2-bf36e11792d1.png)
![3](https://user-images.githubusercontent.com/117596825/235345740-1450cb50-6a6f-4ab3-9a34-0f3867298ab7.png)

**Comment by CriticalFlaw** [comment]
Submit a PR if you already made the change

**Comment by CriticalFlaw** [comment]
Better to overlap, I suppose.
