### ISSUE TITLE
[REQUEST] DisguiseStatusPanel overlaps the CurrencyStatusPanel in MvM

### ISSUE THREAD

**Issue by Whurrhurr** [CriticalFlaw/TF2HUD.Fixes#146]
title. also obscures how many credits you currently have.

![image](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/33162051/6a9b5246-5a44-453b-bb33-ccb1e47fd34f)

solution: make CurrencyStatusPanel in hudlayout.res have a ypos of r88 (and remove the ypos_minmode line, as that's the same ypos that minmode uses) and change the xpos of InWorldCurrencyPanel in hudmannvsmachinestatus to 85 so that you get this:

![image](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/33162051/ebc21399-a3b0-45b4-8ab3-b0a54136885e)
while there is a small bit of overlap between the CurrencyStatusPanel and DisguiseStatusPanel, you can at least see how many credits you currently have without needing to visit an upgrade station.

**Comment by CriticalFlaw** [comment]
I think this may be too niche because this is only applicable to Spies in MvM. To really fix it would mean to change position of it for everyone.

**Comment by mtxfellen** [comment]
A simple modification of the zpos of the elements may be preferable (to have money draw over the disguise panel) given that bot name/weapon selection has no bearing in MvM, only class choice in the instance of using YER.

**Comment by CriticalFlaw** [comment]
The killstreak also gets overlapped by it - to stay consistent with how that issue was addressed. It's best to leave this as-is.

**Comment by CriticalFlaw** [comment]
Closing as not planned. Since the spy disguise overlaps the killstreak counter, it will also overlap the mvm cash counter.
