### ISSUE TITLE
[BUG] Dashboard overlaps top-right console debug info

### ISSUE THREAD

**Issue by TeutonicTea** [CriticalFlaw/TF2HUD.Fixes#147]
**Issue**
The dashboard overlaps the debug info that appears in the top-right when the console is visible.

**Specifications**
1920x1080

**Screenshots**

https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/21269703/7c366d0f-4f40-4d55-b90f-150e350fdedb

**Comment by CriticalFlaw** [comment]
I'd report that to Valve themselves tbh - I don't think this is a valid bug for this HUD project.
