### ISSUE TITLE
[REQUEST] Revert TF2 Secondary font changes back to default

### ISSUE THREAD

**Issue by ArmorKeik** [CriticalFlaw/TF2HUD.Fixes#148]
**Is your feature request related to a problem? Please describe.**
When in the Community version (full version) they updated the source of the engineer panel they also did it in the Workshop version (fixes only).

**Additional context**
![](https://cdn.discordapp.com/attachments/735687611456159767/1116794478825574521/image.png)
Some time ago I asked if this was a mistake and you told me that the font change was not intentional (#68).
So my suggestion is to revert this change or at least leave a comment to know how to do it manually.

**Comment by CriticalFlaw** [comment]
This can be reverted manually by deleting the following files from `resource/ui/` folder:
- [hud_obj_dispenser.res](https://github.com/CriticalFlaw/TF2HUD.Fixes/blob/main/resource/ui/hud_obj_dispenser.res)
- [hud_obj_sentrygun.res](https://github.com/CriticalFlaw/TF2HUD.Fixes/blob/main/resource/ui/hud_obj_sentrygun.res)
- [hud_obj_sentrygun_disp.res](https://github.com/CriticalFlaw/TF2HUD.Fixes/blob/main/resource/ui/hud_obj_sentrygun_disp.res)
- [hud_obj_tele.res](https://github.com/CriticalFlaw/TF2HUD.Fixes/blob/main/resource/ui/hud_obj_tele.res)
- [hud_obj_tele_entrance.res](https://github.com/CriticalFlaw/TF2HUD.Fixes/blob/main/resource/ui/hud_obj_tele_entrance.res)
- [hud_obj_tele_exit.res](https://github.com/CriticalFlaw/TF2HUD.Fixes/blob/main/resource/ui/hud_obj_tele_exit.res)

**Comment by ArmorKeik** [comment]
> This can be reverted manually by deleting the following files from `resource/ui/` folder:
> 
> * [hud_obj_dispenser.res](https://github.com/CriticalFlaw/TF2HUD.Fixes/blob/main/resource/ui/hud_obj_dispenser.res)
> * [hud_obj_sentrygun.res](https://github.com/CriticalFlaw/TF2HUD.Fixes/blob/main/resource/ui/hud_obj_sentrygun.res)
> * [hud_obj_sentrygun_disp.res](https://github.com/CriticalFlaw/TF2HUD.Fixes/blob/main/resource/ui/hud_obj_sentrygun_disp.res)
> * [hud_obj_tele.res](https://github.com/CriticalFlaw/TF2HUD.Fixes/blob/main/resource/ui/hud_obj_tele.res)
> * [hud_obj_tele_entrance.res](https://github.com/CriticalFlaw/TF2HUD.Fixes/blob/main/resource/ui/hud_obj_tele_entrance.res)
> * [hud_obj_tele_exit.res](https://github.com/CriticalFlaw/TF2HUD.Fixes/blob/main/resource/ui/hud_obj_tele_exit.res)

Thank you very much for the quick answer!

Checking the HUD further I see that there are several font changes made in the workshop version and I would like to make a suggestion to revert them (or at least know how to revert it on my own as you showed me above) since I don't agree with fonts being changed in a version that should only fix bugs.

Should I create another Issue for this or leave it in a comment? @CriticalFlaw

**Comment by CriticalFlaw** [comment]
The font change won't be reverted. You can delete the files you don't want to use to fit your needs.

**Comment by ArmorKeik** [comment]
> The font change won't be reverted. You can delete the files you don't want to use to fit your needs.

Understood, so if it's not too much trouble, please tell me how to revert these font changes (I don't know if there are more from other parts of the HUD but these were the ones I noticed).

### Multiplayer score

**DEFAULT**

![](https://cdn.discordapp.com/attachments/735687611456159767/1116826331808800798/image.png)

**MOD**

![](https://cdn.discordapp.com/attachments/735687611456159767/1116827345144250419/image.png)

### List of deaths

**DEFAULT**

![](https://cdn.discordapp.com/attachments/735687611456159767/1116817319046434856/image.png)


**MOD**

![](https://cdn.discordapp.com/attachments/735687611456159767/1116818491333414923/image.png)

_And since we are talking about reverting changes, could you tell me again how to return the bottom panel of the player list?
It happens that I can't find [the configuration](https://github.com/CriticalFlaw/TF2HUD.Fixes/issues/20#issuecomment-932835632) in `hudmatchstatus.res` that it told me to change. (#20)_ 

**DEFAULT**

![image](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/87909542/ea0ea0f7-cc45-48b9-a714-7ec250babc40)

**MOD**

![image](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/87909542/e47fac3a-9435-427e-844a-fc583d78e1b2)

I don't ask for anything more than that.
Thank you for your attention and hope you have a nice day.

**Comment by CriticalFlaw** [comment]
The font change has been reverted in the `main` branch. The font change will be offered as a separate customization option in the future.
