### ISSUE TITLE
[REQUEST] Make kills/death bigger

### ISSUE THREAD

**Issue by monsef987** [CriticalFlaw/TF2HUD.Fixes#150]
on scoreboard (TAB) can you make kills and deaths bigger so it will be easier to read? example like idhud 'improved default hud'

**Comment by CriticalFlaw** [comment]
The font used in this HUD is only 1 point smaller than the one in idhud, which isn't even modified - it uses the same verdana font as the default HUD.

**Comment by monsef987** [comment]
> The font used in this HUD is only 1 point smaller than the one in idhud, which isn't even modified - it uses the same verdana font as the default HUD.

never saw that, well is it good suggestion?

**Comment by CriticalFlaw** [comment]
The size of the killfeed does not need to be changed.
