### ISSUE TITLE
error in changelogs on steam

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/TF2HUD.Fixes#151]
>Fixed briefcase icon overlapping timer/powerup in Mannpower.

This fix was only for the TF2HUD.Fixes, in the Default Hud everything was fine

**Comment by CriticalFlaw** [comment]
Can you provide the link to the changelog that lists this change?

**Comment by CriticalFlaw** [comment]
Removed from the changelog. I could have sworn it was part of the default HUD but must have gotten it mixed it. Thanks!
