### ISSUE TITLE
[BUG] Summer event main menu grill doesn't appear

### ISSUE THREAD

**Issue by kittenchilly** [CriticalFlaw/TF2HUD.Fixes#152]
**Issue**
The new grill used on the main menu during the summer event does not appear with the mod on.

**Specifications**
I'm using the Complete branch, but it might be the same on the normal branch as well.

**Screenshots**
![20230724124420_1](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/23617175/dfa30a44-e767-492a-a9fa-e02ffb3a991f)

**Comment by ArmorKeik** [comment]
![image](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/87909542/9e847f82-aed0-4e73-852e-17effeb28c2a)
I can see it and also using your same version

**Comment by kittenchilly** [comment]
Nevermind, it seems it was because of another mod I had installed, I believe. I can see it now after deleting that mod.
