### ISSUE TITLE
[REQUEST] Add selbyen custom icons

### ISSUE THREAD

**Issue by Foxydapirate12** [CriticalFlaw/TF2HUD.Fixes#154]
This suggestion isn't related to a problem but i found some mods that might be of some use to this, i'll provide links bellow:
[VSH HUD Element](https://gamebanana.com/mods/460190)
[Selbyen HUD Icons](https://gamebanana.com/mods/459755)

I hope that this is of some help, in any way ^w^

**Comment by Foxydapirate12** [comment]
Oh also the [Custom MvM Missions Fixes](https://github.com/CriticalFlaw/TF2HUD.Fixes/pull/149) Pull Request is Pending Review. (Just adding this in case it was forgotten)

**Comment by CriticalFlaw** [comment]
> Oh also the [Custom MvM Missions Fixes](https://github.com/CriticalFlaw/TF2HUD.Fixes/pull/149) Pull Request is Pending Review. (Just adding this in case it was forgotten)

Reviewed and merged.

**Comment by CriticalFlaw** [comment]
Added in 88b861c38c186a00bb107f99624c4fffbc7eb418. Credit to @aarmastah for creating and sharing the icons
