### ISSUE TITLE
Black Bars visible on skinned items in 1440p resolutions

### ISSUE THREAD

**Issue by Presto06** [CriticalFlaw/TF2HUD.Fixes#155]
![image](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/123919000/655edfcc-5c5d-4326-9f14-ece70d99a4c0)

Found this on the Huds.tf discord tried it out myself and it looks good and fixes the darned black bars

All credits to Selbi on discord

Changes applied:
![image](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/123919000/beb1aafe-deac-474b-ae9a-a518d53b0906)

**Comment by CriticalFlaw** [comment]
I'm aware of the fix since it's been added to bud, flaw and hypnotize huds. I'm honestly wondering if there's a better way valve could fix it - but if not then it can be added in

**Comment by Presto06** [comment]
> I'm aware of the fix since it's been added to bud, flaw and hypnotize huds. I'm honestly wondering if there's a better way valve could fix it - but if not then it can be added in

Yeah true, What I would do is add it to the hud version of the fixes (the one in the hud editor) that comes with all the misc features and then leave the fixes being sent to valve as is

Your choice though, your project

**Comment by CriticalFlaw** [comment]
Fixed in fabdd6a32467f5d0da276f6f45fade84958fad13
