### ISSUE TITLE
[BUG] PD animation for score counter is triggering in minmode

### ISSUE THREAD

**Issue by Whurrhurr** [CriticalFlaw/TF2HUD.Fixes#157]
**Issue**
load any player destruction map with minmode hud enabled and have the minmode player destruction hud extra installed and have either team score a point, their score text will be misplaced, but the shadow text is not misplaced.

**Screenshots**
![image](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/33162051/19058298-38b8-4790-95f5-f1a355f345cb)
![image](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/33162051/5f6e33d1-8147-4cf4-a206-c257fc6eb6ce)

**Comment by Whurrhurr** [comment]
i was (at the time of writing this issue) using the base branch, which doesn't have those events in hudanimations_custom.txt.

**Comment by CriticalFlaw** [comment]
I think that minmode variant was removed from the base branch since then due to these issues. The complete branch has the fix.
