### ISSUE TITLE
[REQUEST] Add Fixed TF2 Secondary font mod

### ISSUE THREAD

**Issue by kittenchilly** [CriticalFlaw/TF2HUD.Fixes#158]
**Is your feature request related to a problem? Please describe.**
Specifically if it'd be ok with the creator of the mod, for this to be added:
https://gamebanana.com/mods/466197

**Additional context**
![image](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/23617175/e600203a-babc-4b33-b020-df6e3f532c4a)

**Comment by CriticalFlaw** [comment]
Is this only happening in certain resolutions? On my end without the mod, everything looks fine: 
![image](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/6818236/ce3ae020-cc7e-4d43-85c6-ce847305ab54)

**Comment by CriticalFlaw** [comment]
Sure, go for it.

**Comment by CriticalFlaw** [comment]
It seems too oddly specific to only happen in those resolutions. Also TF2HUD.Fixes does not add any new font entries so it would make no sense for it to be causing this issue.

**Comment by CriticalFlaw** [comment]
I'm more inclined to leave it with the original author and have them send it to valve to fix themselves

**Comment by CriticalFlaw** [comment]
They're using entirely different fonts. The mod seems to fix an issue with TF2 Secondary that does not consistently exist in hud-fixes unless you're on a specific resolution and even then it's not guaranteed.
