### ISSUE TITLE
[FIXED] SELECT STYLE PREVIEW MODELS NOT SHOWING

### ISSUE THREAD

**Issue by epicrockhopper** [CriticalFlaw/TF2HUD.Fixes#159]
For items such as the Bird-Man of Aberdeen and The Splendid Screen, when switching style, the preview model doesn't show. "hud_reloadscheme" does not fix it.

This may be a resolution issue, I use 1980x1080. I use Windows.
I have used the .extras folder.

I do have sceenshots. Any help would be appreciated.
![20231101184034_1](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/149509370/b5a90587-65aa-4b19-b9b4-bb5a23e5da43)
![20231101183955_1](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/149509370/f1e4d8b1-bc3a-4831-8e7f-1e600e3e4dc3)

**Comment by mtxfellen** [comment]
fix posted in huds.tf discord by DarSitam
![image](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/21310017/e5e240a2-c0e7-4f55-9e9b-bda572065e67)

**Comment by CriticalFlaw** [comment]
Reopened because the proposed fix did not address the issue. @mtxfellen

**Comment by CriticalFlaw** [comment]
You're correct, my apologies. Fixed in 237abdb1ae52fd023a56f5f0027525ba777f55c8
