### ISSUE TITLE
Suggestion: fix Bazaar Bargain's headshot counter

### ISSUE THREAD

**Issue by Tiagoquix** [CriticalFlaw/TF2HUD.Fixes#16]
https://wiki.teamfortress.com/wiki/Bazaar_Bargain#Bugs

**Comment by CriticalFlaw** [comment]
I was not able to reproduce it. The counter appears in both hud-modes, regardless of what secondary is equipped.

![20210605133649_1](https://user-images.githubusercontent.com/6818236/120900533-269da800-c603-11eb-8d19-b69aec6a407e.jpg)

![20210605133654_1](https://user-images.githubusercontent.com/6818236/120900535-27363e80-c603-11eb-8895-2d9f56152bdc.jpg)

**Comment by TheThunderGuyS** [comment]
Any counters disappearing is a bug within TF2 itself, and can be fixed by running `record fix; stop` in the console.
