### ISSUE TITLE
[BUG] Vote HUD's scroll bar overlaps player's time on server

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/TF2HUD.Fixes#161]
**Issue**
https://github.com/ValveSoftware/Source-1-Games/issues/5074
This happens when there are more than 12 players on the same team

**Specifications**
Operating system - Windows 11 Enterprise 22H2
Resolution - 1920x1080

**Screenshots**
![votehud](https://github.com/ValveSoftware/Source-1-Games/assets/117596825/3218d23d-99d8-4506-96a6-2a3c25f878e3)
![votehud2](https://github.com/ValveSoftware/Source-1-Games/assets/117596825/06b5385f-9e26-4817-8ed9-5412fbed3d34)

**Comment by CriticalFlaw** [comment]
How is that a problem?

**Comment by CriticalFlaw** [comment]
I disagree, it's a negligible yet necessary change. It does not make the experience worse.

**Comment by CriticalFlaw** [comment]
Yeah, it would necessitate an entire redesign which is not inscope for this project.

**Comment by CriticalFlaw** [comment]
Fixed in 60397f9d13eda2b73766eb672d8357a75703a98c
