### ISSUE TITLE
[BUG] Button overlaps on shared notification panel

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/TF2HUD.Fixes#163]
`TF2HUD.Fixes` -> `resource` -> `ui` -> `upgradeboxdialog.res`
**Issue**
The buttons touch the text at the top and overlap each other

**Specifications**
Operating system - Windows 11 Enterprise 22H2
Resolution - 1920x1080

**Screenshots**
![image](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/117596825/d0c355a2-6c1a-4dee-830c-e93a21ce749c)

**Comment by CriticalFlaw** [comment]
Can you open a PR for this please? I have too much free space in my inventory so I can't get to this screen.

**Comment by CriticalFlaw** [comment]
the issue is that a lot of these panels are either hardcoded or tied to a shared file which does not account for panel variants and hence some obscure ones like this one break. I'll leave it to you or anyone else to take a stab at it.
