### ISSUE TITLE
[BUG] On the crafting panel, the scroll bar is almost the same color as the background

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/TF2HUD.Fixes#164]
`TF2HUD.Fixes` -> `resource` -> `ui` -> `craftingpanel.res` -> `"recipecontainerscroller"`

**Specifications**
Operating system - Windows 11 Enterprise 22H2
Resolution - 1920x1080

Steps to reproduce the issue:
1. In the main menu on the bottom left, click the Items button
2. Click the Crafting button
3. Click the Common items button at the top left

**Screenshots**
![scrollbarcolor](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/117596825/b88c2fcc-8840-4c13-955b-1d75ce5bd7ff)

**Comment by CriticalFlaw** [comment]
That's not a bug. It looks to be an intentional choice.

**Comment by CriticalFlaw** [comment]
I think it's best to leave it as-is. Thank you for suggesting it though.
