### ISSUE TITLE
Is anyone else having trouble with this mod?

### ISSUE THREAD

**Issue by AChristianGamer** [CriticalFlaw/TF2HUD.Fixes#17]
I've used it in the past (before I had to reinstall Windows because of a corrupted backup, It's a long story) and it worked fine then, but now for some reason It's not doing anything.  I simply copied/pasted the folders into TF then let Microsoft 10 merge them, am I doing something wrong?  I also didn't paste the info.vdf and README.md because I read them with Notepad++ and they seemed to just tell what changes had been made in it's new version 3 update.

**Comment by CriticalFlaw** [comment]
You're supposed to download the mod and extract it into your `tf/custom` directory.

**Comment by AChristianGamer** [comment]
Oh okay, Thanks!  I'll make a note of that for myself!

**Comment by TheThunderGuyS** [comment]
HUDs must always install to tf/custom. If you install into the root directory they will not work because the signed VPKs overwrite them.
