### ISSUE TITLE
[BUG] Supernova meter overlaps with other meters

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/TF2HUD.Fixes#173]
**Specifications**
Operating system - Windows 11 Enterprise 22H2
Resolution - 1920x1080
Minmode is used

**Screenshots**
![image](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/117596825/f857596c-b6e6-4b3e-9519-bf288aaec3e1)

**Comment by CriticalFlaw** [comment]
getting very nitpicky huh

**Comment by CriticalFlaw** [comment]
updated in a91790b2f78e14eb1bf12cdc483017d8188965ff moved it up higher just to be safe
