### ISSUE TITLE
[BUG] The labels of the taunt slot sometimes appear cut

### ISSUE THREAD

**Issue by Ashetf2** [CriticalFlaw/TF2HUD.Fixes#175]
**Issue**
This issue occurs in the loadout taunt section. The labels "Taunt X" get cut apparently randomly, but I've consistently reproduced this bug by adding and removing a taunt, as you can see in the image. This issue has been annoying the tf2 wiki for a while.

**Specifications**
Retail bug, not using the custom hud

**Screenshots**

![image](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/63692647/1c211d68-f862-4866-8294-da0fb9a6afe1)

**Comment by CriticalFlaw** [comment]
The cutoff looks to coorelate to there being a taunt in that slot in another loadout preset. For example if you have a taunt in slot 1, preset a then go to preset B the label will become cutoff. This persists until a game restart even if you take the taunt off. May be a game issue and the only way to fix it here may be to reduce the font size.

**Comment by CriticalFlaw** [comment]
Looks to have fixed it in https://github.com/CriticalFlaw/TF2HUD.Fixes/commit/d7e3ec9bb50285fa5987fee77460b81248b0dbb0 by changing the label's textAlign from `south` -> `center`. Please redownload and re-test.

Examples - "Taunt 1" and "Taunt 5" look to only now be cutoff by a pixel or so. Let me know what you think.
![20231218233830_1](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/6818236/57de5c7e-3f4b-4f49-9957-cf7b2b981440)
![20231218233834_1](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/6818236/d17886df-b3b6-43aa-8723-fdf1b60937f9)

**Comment by CriticalFlaw** [comment]
(re-opened until @Ashetf2 retests)

**Comment by Ashetf2** [comment]
I can confirm that it's fixed, or at least I couldn't replicate the bug anymore. Thanks!

**Comment by CriticalFlaw** [comment]
> I can confirm that it's fixed, or at least I couldn't replicate the bug anymore. Thanks!

No problem. Thank you for testing :)
