### ISSUE TITLE
[BUG] Weapon selection label collides with search bar

### ISSUE THREAD

**Issue by Eerorri** [CriticalFlaw/TF2HUD.Fixes#178]
**Issue**
The ItemSlotLabel collides with the search bar

**Specifications**
OS: Linux, Res: Any (?), Steps to reproduce: Install the HUD and open the weapon selection panel

**Screenshots**
![dt2dmIH](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/97610612/e4169c3b-bf8e-4993-80e0-c748103013ee)
![Screenshot_20231227_020120](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/97610612/dbd094d4-34ec-48fb-9f51-97ea3f480f0a)

Can be fixed by modifying "ItemSlotLabel" in itemselectionpanel.res by making xpos c-155 instead of c-55

![Screenshot_20231227_020641](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/97610612/6a64f3f5-b725-4e1f-8ebe-07f14e303f57)
![Screenshot_20231227_021401](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/97610612/977ce1b7-cfb8-4d66-bdce-debf3faf3b24)

**Comment by CriticalFlaw** [comment]
Can you submit a PR with this change and also test to make sure there are no overlaps with any other class name.

**Comment by Eerorri** [comment]
Made pull request

**Comment by CriticalFlaw** [comment]
Much appreciated
