### ISSUE TITLE
Unfixed bugs and suggestion for voice chat

### ISSUE THREAD

**Issue by ArmorKeik** [CriticalFlaw/TF2HUD.Fixes#18]
These mods are very good, I hope Valve accepts the suggestion so that everyone can enjoy these fixes and improvements. I only have two drawbacks with this HUD Fix.

  **1.** It does not solve the error of the list of players, which appears at the top, in the Arena mode (Two lists are combined, the one that counts the players by teams/classes and the one that lists the players. Covering the top of the second list; the one that lists.).

![20210722153309_1](https://user-images.githubusercontent.com/87909542/126876046-80e8ef95-1c69-4f89-80e2-5d97b12c44d0.jpg)
![20210722153313_1](https://user-images.githubusercontent.com/87909542/126876056-258991d4-1b24-409d-9974-ad142c4c9a5b.jpg)

  **2.**  At the end of the Arena mode rounds, a menu appears showing the top 3 players from both teams.It turns out that (I only looked at the Spanish language), the part that lists the victims is misplaced and appears coming out of the menu.

![20210722182342_1](https://user-images.githubusercontent.com/87909542/126877007-9721e20a-a975-4954-8a81-b2eb66ab2f67.jpg)

TIP FOR VOICE CHAT _(Optional, breaks the original aesthetics of the game, but adds a better flair):_

**1.** Add the avatar of who is using the microphone like some HUDs do (I'll leave two examples below).

![descarga](https://user-images.githubusercontent.com/87909542/126877273-88d2dc1d-fba0-4c42-82fc-5dfc09f721e6.png)
![maxresdefault](https://user-images.githubusercontent.com/87909542/126877282-48674787-25b4-4106-8e82-7c3bc03c64a9.jpg)

**Comment by ArmorKeik** [comment]
### Hello, I come to report other errors that this mod  does not solve.

### MAIN MENU:

**1.** The message to confirm if you want to quit the game has the letter R cut out (or at least in Spanish).

![Captura de pantalla (31)](https://user-images.githubusercontent.com/87909542/127391618-4c579069-b263-4044-a78b-8179266a341c.png)

**2.** Sometimes you can get bugged alerts. Either only the number appears or it is invisible, but you hear the noise and you can press it to open it (unfortunately I can't take a screenshot of this, but I'll leave you an image so you know what I'm talking about).

![GUI_Main_Menu_Alert_Button](https://user-images.githubusercontent.com/87909542/127391743-7137fb0e-2d28-4e51-bf4c-17d44295f910.png)


### MULTIPLAYER SCORES:

**1.** The table to see the game info has the number 9 cut off.

![Captura de pantalla (33)](https://user-images.githubusercontent.com/87909542/127391683-8138af0d-1de0-4b96-94ee-63b398f7d477.png)

PS: I translated both messages with Google Translate.

**Comment by ArmorKeik** [comment]
I recently encountered another bug in the game again.

When they dropped a gun on me, it came **without a description**, only the image of the model was visible.

https://user-images.githubusercontent.com/87909542/127748437-aad71be3-1630-491f-8a2d-eab33e313112.mp4

**Comment by ArmorKeik** [comment]
Hello CriticalFlaw, taking advantage of the fact that you saw my topic, I take the opportunity to send you more errors that I found.

**1.** This one had already notified you, but now I show it to you with screenshots. The invisible notifications.

![Captura de pantalla (43)](https://user-images.githubusercontent.com/87909542/129394030-efff5be4-c22e-40b9-ac03-bdb79bc15882.png)
![Captura de pantalla (44)](https://user-images.githubusercontent.com/87909542/129394038-0d0c745c-0029-4d3c-8007-07fb00711eaa.png)

**2.** This could already be seen in the message to confirm the exit, but here I show you more examples. Confirmation notifications are not centralized.

![Captura de pantalla (97)](https://user-images.githubusercontent.com/87909542/129398301-8b3d79e7-aaca-4aee-9238-f1d2eff32c62.png)
![Captura de pantalla (98)](https://user-images.githubusercontent.com/87909542/129398305-3ad579cd-12ae-4036-b9f4-80a91527dba6.png)

**3.** A minimal error (perhaps), which appears when entering any server.
If you open the menu while playing the game, the vote button will always appear red. Even if you uncheck it, it will be marked red again when you open the menu again. A minimal error (perhaps), which appears when entering any server.
If you open the menu while playing the game, the vote button will always appear red. Even if you uncheck it, it will be marked red again when you open the menu again.

![Captura de pantalla (99)](https://user-images.githubusercontent.com/87909542/129399059-a7920e04-9261-4435-8529-8ee81caaea2b.png)

**4.** In the Objects > Equipment section there is an error with the presentation of the description of the subsections below.
The descriptions of the objects of the classes are fine, but the ones below are not, when hovering the mouse over them nothing is shown, you are forced to have to pass them below to be read, although sometimes this also fails.

https://user-images.githubusercontent.com/87909542/129402878-e622ddfd-5a6b-4b7a-a057-22caf8a1649e.mp4

**5** And finally, a mistake that is very, very minimal. The letters "s" are very close together. This is in the Workshop section, within TF2 (Spanish).

![Captura de pantalla (100)](https://user-images.githubusercontent.com/87909542/129404417-649653ba-09a9-4816-b47d-3290144509fa.png)

Thanks for reading me and thanks for creating this mod.
All these messages I translated with the Google translator.

**Comment by CriticalFlaw** [comment]
> **1.** It does not solve the error of the list of players, which appears at the top, in the Arena mode (Two lists are combined, the one that counts the players by teams/classes and the one that lists the players. Covering the top of the second list; the one that lists.).

This is intentional and you can remove the player list by entering `tf_use_match_hud 0` into console.

> **2.** At the end of the Arena mode rounds, a menu appears showing the top 3 players from both teams.It turns out that (I only looked at the Spanish language), the part that lists the victims is misplaced and appears coming out of the menu.

That may only be happening in other languages, but I'll see if it's an issue in English.

> **1.** Add the avatar of who is using the microphone like some HUDs do (I'll leave two examples below).

It's not a bad idea, I don't know why it was removed in the first place but I'll see if it can be re-enabled.

> 1. The message to confirm if you want to quit the game has the letter R cut out (or at least in Spanish).

The TF2 has multiple issues rendering its own font, often seen when playing in other languages. Correcting these kind of issues are out of scope for this project.

> 2. Sometimes you can get bugged alerts. Either only the number appears or it is invisible, but you hear the noise and you can press it to open it (unfortunately I can't take a screenshot of this, but I'll leave you an image so you know what I'm talking about).

That's a known game bug, it cannot be fixed using HUD files, at least to my knowledge.

> 1. The table to see the game info has the number 9 cut off.

See above, font rendering issues are out of scope.

> When they dropped a gun on me, it came without a description, only the image of the model was visible.

Game bug, cannot be fixed with HUD files.

> 2. This could already be seen in the message to confirm the exit, but here I show you more examples. Confirmation notifications are not centralized.

This one should be fixable, it was broken in Jungle Inferno if I recall correctly. Will take a look, thanks!

> 3. A minimal error (perhaps), which appears when entering any server. If you open the menu while playing the game, the vote button will always appear red. Even if you uncheck it, it will be marked red again when you open the menu again. A minimal error (perhaps), which appears when entering any server.

That may be due to that button being set as the default in the tab order. I'm not sure if that can be corrected, but I'll take a look.

> 4. In the Objects > Equipment section there is an error with the presentation of the description of the subsections below.
The descriptions of the objects of the classes are fine, but the ones below are not, when hovering the mouse over them nothing is shown, you are forced to have to pass them below to be read, although sometimes this also fails.

This is a game bug and the TF team had already been notified of it via email and on GitHub, but I don't think they plan on fixing it. https://github.com/ValveSoftware/Source-1-Games/issues/3296

> 5 And finally, a mistake that is very, very minimal. The letters "s" are very close together. This is in the Workshop section, within TF2 (Spanish).

Another font related issue.

Thank you very much for reporting these issues. Unfortunately not all of them can be addressed but I appreciate you bringing them forward. I'll look into correcting the ones I can in the near future. Cheers

**Comment by ArmorKeik** [comment]
Oh I see.
No problem, thanks for reading my issue and for continuing to maintain this project.
I hope Valve could correct the bugs in the game I put here, but that sounds almost impossible.
Greetings.

**Comment by CriticalFlaw** [comment]
> **1.** Let's go first with the bug. The thermal thruster gauge looks **badly positioned**, contrary to how it looked in the demo video.
> 
That can be corrected.

> **2.** Now the suggestion. In the Create Server section you can select maps from a simple menu, but SO SIMPLE that it does not let you search for the maps from a text search engine (as if we were in a browser or in the Windows menu). So I suggest adding this feature to make it much **more convenient** to search for the map you want to use (especially if you have a lot of maps).
> 
This cannot. I cannot add a search function if there's no functionality coded for that.

**Comment by CriticalFlaw** [comment]
- Lowered the player count in Arena Mode so to not overlap the match hud.
- Added player avatars to the voice indicator.
- Corrected the positioning of Thermal Thruster elements.

Thank you for reporting these issues 1b5e072cb1b0091d28a0b6beafea4db7b8c3779e
