### ISSUE TITLE
[BUG] Multiple item meters/counters overlap in 4:3

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/TF2HUD.Fixes#186]
**Specifications**
Operating system - Windows 11 Enterprise 22H2
Resolution - 640x480

**Screenshots**
![image](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/117596825/211be68e-df07-4f12-adde-4cb82c65e076)

**Comment by CriticalFlaw** [comment]
I'm going to consolidate all the 4:3 item meters issues into one, because they are all the same issue.

**Comment by CriticalFlaw** [comment]
Soda Popper
![302431319-422a3abe-a628-4906-adbe-bdbbf814ccf2](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/6818236/fcd09b2d-2557-44cc-8962-1ae9105514c3)

Air Strike
![302433158-2b7c096c-26c6-477a-9322-11ec6351eb89](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/6818236/85789f76-b7f9-43b4-b1e6-d5976808542a)

Manmelter
![302434796-2c3ae165-954a-4ecd-8fab-429ea9364f3c](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/6818236/a9cc8418-b26e-4210-8441-6a0ecef26dfe)

Pomson
![302435796-f4897c98-5491-440d-a53f-90ddeee16bd8](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/6818236/901204a5-0208-4995-8832-6d4f9370ca06)

Vita-Saw
![302436361-b9900b49-4300-4e78-bef0-b9fcd4756ee6](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/6818236/d2fac101-982e-416b-8777-36a73ed6d01e)

Bazaar Bargain
![302440665-c2fa09dd-181d-4f69-a763-e50fa1919264](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/6818236/55e1884b-cefe-4154-8794-91d5e938a9de)

**Comment by CriticalFlaw** [comment]
I've spent a few hours today trying to adjust for this but ultimately think it's not doable.

The biggest issue is the objective UI (CTF, Payload etc.) which cannot be scaled depending on the current resolution, and it doesn't make sense to try and move or re-design the item meters to accommodate for it. Moving them would just make it worse for people playing on 16:9 and above which would be majority of players.

The workaround would be to just use minmode which uses smaller objective UI for CTF and moved meters to the side.

**Comment by CriticalFlaw** [comment]
> Game modes without minmode support: PASS Time Payload Race

Opened https://github.com/CriticalFlaw/TF2HUD.Fixes/issues/208 for this

**Comment by CriticalFlaw** [comment]
@impale1 reassigning to you to look into this

**Comment by CriticalFlaw** [comment]
@impale1 will you be looking into this one or no?
