### ISSUE TITLE
[BUG] Soda Popper meter overlaps the objective in a 4:3 aspect ratio

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/TF2HUD.Fixes#187]
**Specifications**
Operating system - Windows 11 Enterprise 22H2
Resolution - 640x480

**Screenshots**
![image](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/117596825/422a3abe-a628-4906-adbe-bdbbf814ccf2)

**Comment by CriticalFlaw** [comment]
Closing as duplicate of #186
