### ISSUE TITLE
[BUG] Pomson meter overlaps the objective in a 4:3 aspect ratio

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/TF2HUD.Fixes#190]
**Specifications**
Operating system - Windows 11 Enterprise 22H2
Resolution - 640x480

**Screenshots**
![image](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/117596825/f4897c98-5491-440d-a53f-90ddeee16bd8)

**Comment by CriticalFlaw** [comment]
Closing as duplicate of #186
