### ISSUE TITLE
[BUG] Vita-Saw counter overlaps the objective in a 4:3 aspect ratio

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/TF2HUD.Fixes#191]
**Specifications**
Operating system - Windows 11 Enterprise 22H2
Resolution - 640x480

**Screenshots**
![image](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/117596825/b9900b49-4300-4e78-bef0-b9fcd4756ee6)

**Comment by CriticalFlaw** [comment]
Closing as duplicate of #186
