### ISSUE TITLE
[BUG] Bazaar Bargain counter touches the objective in a 4:3 aspect ratio

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/TF2HUD.Fixes#192]
**Specifications**
Operating system - Windows 11 Enterprise 22H2
Resolution - 640x480

**Screenshots**
![image](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/117596825/c2fa09dd-181d-4f69-a763-e50fa1919264)

**Comment by CriticalFlaw** [comment]
Closing as duplicate of #186
