### ISSUE TITLE
[BUG] Gas Passer meter label is written in lower case

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/TF2HUD.Fixes#193]
All other meter labels are in upper case

**Specifications**
Operating system - Windows 11 Enterprise 22H2
Resolution - 1920x1080

**Screenshots**
![gas](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/117596825/92c25b5e-4c48-47c4-abf8-1359df96b56b)

**Comment by CriticalFlaw** [comment]
Ended up reverting this change because it causes the Razorback text to get cut off.

103093729c2264662185f655c248f6c22adfbcfc
