### ISSUE TITLE
[BUG] Intelligence image in the spectator is too big

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/TF2HUD.Fixes#195]
To reproduce this, you need to spectate a player who carries intelligence

**Specifications**
Operating system - Windows 11 Enterprise 22H2
Resolution - 640x480

**Screenshots**
![image](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/117596825/e079f192-e919-4731-8ba4-1b4bcacb725c)

**Comment by CriticalFlaw** [comment]
This is not a bug. For some reason valve wanted it big
