### ISSUE TITLE
[BUG] Razorback meter label is cut off

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/TF2HUD.Fixes#196]
**Specifications**
Operating system - Windows 11 Enterprise 22H2
Resolution - 1920x1080

**Screenshots**
![razorback](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/117596825/dcce4fec-d624-46b3-ae3e-325b8b06969d)

**Comment by CriticalFlaw** [comment]
Probably because of applying all caps for the gas passer. You can have one or the other but not both unless that meter is expanded

**Comment by CriticalFlaw** [comment]
Reverted 103093729c2264662185f655c248f6c22adfbcfc because that change caused this issue. Best to leave it like in the default.
