### ISSUE TITLE
[BUG] Stats from Your best moments are off center

### ISSUE THREAD

**Issue by Presto06** [CriticalFlaw/TF2HUD.Fixes#201]
![image(2)](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/123919000/b6db881a-617d-4606-bcee-85bedd4449d0)

In the stats screen and loading screen the box which shows the stats for "Your Best Moments" is off center

**Comment by CriticalFlaw** [comment]
That's not a bug and is likely this way to accommodate other languages.
