### ISSUE TITLE
[BUG] Killstreak panel overlaps carried weapon panel

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/TF2HUD.Fixes#207]
**Specifications**
Operating system - Windows 11 Enterprise 22H2
Resolution - 1920x1080

**Screenshots**
![carriedweapon](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/117596825/ca7bba1c-6e4d-4df4-b988-2944587df089)

**Comment by CriticalFlaw** [comment]
That panel's width will expand to fit the player's name. So if the player's name is really long it will still overlap.
