### ISSUE TITLE
[BUG] Warning text is cutoff when doing contract

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/TF2HUD.Fixes#210]
**Issue**
You can't see the word "contracts" at the end of the text.

To reproduce:
1. Activate any contract
2. Find the map that the contract demanded
3. Click the disconnect button in the upper right corner

**Specifications**
Operating system - Windows 11 Enterprise 22H2
Resolution - 1920x1080 and 640x480

**Screenshots**
![image](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/117596825/d4d7f26e-e4b3-4c91-8865-2c30808a7042)
Expected behavior:
![image](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/117596825/29c95a58-54da-4b9d-913b-941e2f7984b6)

**Comment by CriticalFlaw** [comment]
is the second screenshot a mockup or in-game fix?

**Comment by CriticalFlaw** [comment]
I see. I think this isn't something that can fixed through the HUD files because the panel size may be tied to the resolution in the code.
