### ISSUE TITLE
[BUG] Contracker red indicator overlaps text

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/TF2HUD.Fixes#212]
**Specifications**
Operating system - Windows 11 Enterprise 22H2
Resolution - 1920x1080

**Screenshots**
![image](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/117596825/14dc71cf-a5f9-4603-8aa2-05603e3e6787)

**Comment by CriticalFlaw** [comment]
Took a look but it looks like the red line is a non-HUD element so there's no way to fix it. The fact this is very niche as well makes it not worth addressing.
