### ISSUE TITLE
[REQUEST] Less obstrusive/obstructive caption styling

### ISSUE THREAD

**Issue by chexo3** [CriticalFlaw/TF2HUD.Fixes#215]
**Is your feature request related to a problem? Please describe.**
Stock TF2 hud's caption styling puts them in the middle of the screen, nice and big. Great for readability in singleplayer games, but terrible for seeing other stuff in multiplayer when the captions are being used with say, clovervidia's captions to display pertinent information. 

**Additional context**
I would like it if there were an option to make the captions text smaller, limit the amount of lines, and remove or make the background behind the text smaller

**Comment by chexo3** [comment]
I think having it centered like stock does is fine. Some huds move it to one side or the other. I just need it to be smaller.

**Comment by chexo3** [comment]
Actually looking in game it might make sense to put it to one side or the other because the objective hud (payload cart, capture points, etc) are in the middle at the bottom of the screen and take up a lot of space. Could also use minimal version of the objective hud with the captions on so that they have more room

**Comment by CriticalFlaw** [comment]
I feel like closed captions are out of scope for this mod. There are various preferences in terms of what people what closed captions to look like and there are plenty of mods on gamebanana that can work alongside this mod. Thank you for the suggestion.
