### ISSUE TITLE
Suggestions and bug reporting

### ISSUE THREAD

**Issue by ArmorKeik** [CriticalFlaw/TF2HUD.Fixes#23]
[This mod](https://gamebanana.com/mods/332109) adds new functions in the create server menu.

It is very useful and does not break with the original aesthetics of the game.

I already tested this mod with several HUDs and **there is no compatibility problem** (because no other mod modifies this menu).

![img.jpg](https://user-images.githubusercontent.com/87909542/143301416-c270d746-a16f-4a78-a96d-10493173504f.jpg)

**Comment by ArmorKeik** [comment]
I report some bugs that I found:

**1.** The text for _"Current wearer attributes:"_ is very low, touching the lower gray line.
This only happens when no attribute is detected.

![Error](https://user-images.githubusercontent.com/87909542/141010965-3f352da0-8959-4b20-a6a1-64314a3c6f51.png)
![Captura de pantalla 2021-10-31 133744](https://user-images.githubusercontent.com/87909542/141011006-7f9e48c4-98de-43d6-a238-f3ba6491cbcb.png)


![Sin error](https://user-images.githubusercontent.com/87909542/141011064-91b52759-9d66-4bea-bffc-d23cb8d1c80b.png)


**2.** This is an error that I have notified you before, but that I still see without solving.
There are still badly centralized posters, I leave you this as an example but there **is still more.**

![Cartel error](https://user-images.githubusercontent.com/87909542/141011575-d7256851-f785-4c8f-a4e0-360ac53fe53b.png)

**Comment by ArmorKeik** [comment]
I also recommend you to add [this mod](https://gamebanana.com/mods/290300) to the HUD Fix, it looks interesting and useful as the one to create servers.

I admit that the _icons are not the best_, but the proposal looks **captivating**.

I didn't test if there is good compatibility because I didn't understand how to download it, but surely you will know how to do it.

![image](https://user-images.githubusercontent.com/87909542/142771571-a0958b68-5068-4d49-ad49-6b871ac01704.png)

![image](https://user-images.githubusercontent.com/87909542/142771582-300247e2-12b1-41c3-9fd2-ee803b14963c.png)

**Comment by ArmorKeik** [comment]
Another suggestion I give you, yes, _it's more than I had intended to send, but more stuff to the game doesn't hurt anyone._

[Add this mod](https://gamebanana.com/mods/25953) that fixes and adds new death icons.

![](https://images.gamebanana.com/img/ss/mods/6041197c92f0b.jpg)

You may find this image or the concept of this mod similar to another one.
But this new mod is a **combination of the best** of the [Missing Killicons Pack](https://steamcommunity.com/sharedfiles/filedetails/?id=2156604959) and the [Consistent Kill Icon Mod: Unofficial Update](https://gamebanana.com/mods/11791).

**Comment by Winth211** [comment]
Source Text Refont [Better Looking Default Text] 

https://gamebanana.com/mods/314848

![611c8197c3a71](https://user-images.githubusercontent.com/82706197/143777042-5c797d77-319c-48bd-aaa2-4085189d6b2c.jpg)

![611c819787c26](https://user-images.githubusercontent.com/82706197/143777045-e10c8b6f-e4d2-449c-a1a3-dba5a16cfb2f.jpg)

**Comment by Winth211** [comment]
HD TF2 Loading Screens  & HD TF2 Menu Logo 

https://gamebanana.com/mods/285046

https://gamebanana.com/mods/27061

![609946bb61f56](https://user-images.githubusercontent.com/82706197/143777565-4a4c789f-914f-4be6-b09d-357fd7e7b105.jpg)

![609946bb8e77a](https://user-images.githubusercontent.com/82706197/143777576-b364fcef-ac12-4e25-96ad-467aecdb64e7.jpg)

![606a96de6f3ff](https://user-images.githubusercontent.com/82706197/143777579-4ee6839b-4f19-4336-98e3-655ca114e549.jpg)

**Comment by valeriedesumo** [comment]
I don't want too many aesthetic changes added to this mod when it's meant to just be hud fixes. It'll lead this mod down the road towards being an actual custom hud because it "looks nicer", especially since a lot of people don't like how the default hud looks.

A big part of this reasoning is that aesthetic changes are subjective, so they may end up looking worse to many people but they get implemented because some other people like it. That font mod in particular is one example, as the new "better" font results in no spacing in "x10", making it harder to read.

**Comment by ArmorKeik** [comment]
> Source Text Refont [Better Looking Default Text]
> 
> https://gamebanana.com/mods/314848
> 
> ![611c8197c3a71](https://user-images.githubusercontent.com/82706197/143777042-5c797d77-319c-48bd-aaa2-4085189d6b2c.jpg)
> 
> ![611c819787c26](https://user-images.githubusercontent.com/82706197/143777045-e10c8b6f-e4d2-449c-a1a3-dba5a16cfb2f.jpg)

I can agree with you on HD mods, but this would already be **breaking the original aesthetics** of TF2.

I know, this mod changes the color of the chat and removes the black bar from the player list (you can undo both changes), but changing the font of the text seems to me that it would not fit with this project.

The thing would be different if it would be a "correction" to the font; since in several languages there are letters and words that are cut off (as is the case of Spanish).

_Now you may say: But your suggestions would also break the original aesthetics of the game._ Well, I wouldn't see it that way, I see it more as adding new features which could easily go in the original game without needing to look different from the original TF2 aesthetics.

**Comment by CriticalFlaw** [comment]
I agree with @valeriedesumo that aesthetic changes don't fit this project, unless it is meant to fix an issue. While that has always been the focus of the project, I admittedly made changes like the new taunt icon and chat color change that go against that - which I indent to correct shortly.

Going forward I'll do a better job of keeping subjective changes out of this mod and try to find a solution for implementing aesthetic - possibly as customization options enabled via the editor or manually.

**Comment by CriticalFlaw** [comment]
Added to Source Fonts (f9d119bc0e0ea13ae326d5e1c0b5870cc1a73f23) and missing killicons (5fa300f03186758a7618827817599e340e0638ab) to the **community** branch only.
