### ISSUE TITLE
[REQUEST] Add principles to TF2HUD.Fixes

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/TF2HUD.Fixes#234]
**Describe the change request.**
Sometimes it's hard to know what's outside the scope of a project, so principles would be helpful

https://developer.gnome.org/hig/principles.html
I was inspired by this and tried to do something similar

I need your help to improve them and add new ones

Examples:
* Adhere to Valve's coding style
* Do not use hacky solutions
* Do not break the visual style of the default HUD

**Comment by CriticalFlaw** [comment]
I appreciate the suggestion but I don't think this is something I want to have to create, maintain or enforce. While the objective of the mod is to fix issues with the default TF2 HUD - it has admittedly become a bit of a grey area in terms of what ends up being added.

My goal with each change is to keep it as light but effective as possible. Meaning that if you compared the mod to the default HUD, side by side the changes were minimal and clear as to what they are meant to address. Of course, that has gotten away from me somewhat with something like the Customization Menu but I digress.

Valve doesn't really have a coding style, at least not with these .RES files and even visuals are not always consistent. I think focusing on correcting issues that may hinder the player experience should be the priority and anything else so long as it does not take away from the default HUD experience as a whole is up for discussion.
