### ISSUE TITLE
[REQUEST] Add guidelines to TF2HUD.Fixes

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/TF2HUD.Fixes#235]
**Describe the change request.**

Without guidelines:
* We test and edit the HUD on a very wide monitor, and because of this there are many overlooked bugs. (Yes, yes, I'm looking at you).
* (Need to come up with more).

https://developer.gnome.org/hig/guidelines.html
I was inspired by this and tried to do something similar

I need your help to improve them and add new ones

Examples:
* When testing TF2HUD.Fixes, start from the most constrained environment (640x480 resolution) and then work your way up to the least constrained one. This not only helps avoid things that will be hard to scale down, but also helps focus the interface and ensure a clean structure.
* First you need to test the HUD in clean TF2, that is, return all settings to default, and only then proceed to test other settings. https://docs.comfig.app/latest/setup/clean_up/#clean-up

**Comment by CriticalFlaw** [comment]
I usually test with the game resolution set to 1920x1080 but ok. The challenge I see (especially with your recent contributions) is that the HUD seems to behave differently on Linux. Some changes may fix a problem on Linux but create a new one in Windows, it becomes a vicious cycle of fixing the same issues over and over again.

Usually I would do a quick sanity check of each PR but other than that I don't have enough spare time in the day to test everything and I instead trust that the PR author has done that test themselves. Contributors are welcome to be more methodical with their submissions but at the same time people have other priorities in life and HUD editing is not high up there for most (including me).
