### ISSUE TITLE
Bugs, suggestion and doubt about the Workshop edition and the Community edition

### ISSUE THREAD

**Issue by ArmorKeik** [CriticalFlaw/TF2HUD.Fixes#24]
First of all I support your idea of separating both editions to please the public who are only looking for the fixes and those who want to add new features to the HUD.

**1.** But both share a bug in adding the [Improved Create Server Menu](https://gamebanana.com/mods/332109) mod.

![Código roto (Community edition)](https://user-images.githubusercontent.com/87909542/144093454-e6665a3f-43a8-488d-afe6-b9f63b5d2589.png)
![Código roto (Workshop edition)](https://user-images.githubusercontent.com/87909542/144093461-90345483-258a-4859-b7b8-332db78f4d92.png)

As you can see, the text of the options is not displayed, but the commands that each option executes are shown (this is odd, as everything looked fine when I tested it with the TF2HUD.Fixes in Issue #23).

**2.** The new font mod, the [Source Text Refont [Better Looking Default Text]](https://gamebanana.com/mods/314848), has errors with the position of the Spanish text and the 1360x738 aspect ratio.

![Mala posición (Community edition)](https://user-images.githubusercontent.com/87909542/144094812-a56abf26-d936-44d7-b7cc-09c4cd1ead8b.png)
![Muertos (Community edition)](https://user-images.githubusercontent.com/87909542/144094834-8017b231-5d4d-439a-a7e2-f7c5afa6d4e9.png)

So I suggest reverting this change back to the original Team Fortress 2 source.

**3.** Seeing that these latest versions in development have bugs, I'm going to stick with the version I had; an edit of 642ec4124b5cd23196a50cfcfd709c989b4c5bca that removes returns the chat to its normal color and returns the black bar in the player menu (basically what you taught me to do in Issue #20).

But I would like to keep the new feature of changing the team color while in loadout (the letter R presents is cut off, but that may be due to my aspect ratio and may not be repairable).

Could you show me how I could add it to the edit I use?

![RED and BLU (Community edition)](https://user-images.githubusercontent.com/87909542/144099080-aa1c2fb1-783f-4225-ace0-fbda8008a0b1.png)
![RED and BLU glitch (Community edition)](https://user-images.githubusercontent.com/87909542/144099082-3c285166-d03d-4d80-b0f0-15cd39fdd577.png)

**Thanks for reading** 😀

**Comment by ArmorKeik** [comment]
**UPDATE:** I remembered that last time I only had to copy codes, so I went [here](https://github.com/CriticalFlaw/TF2HUD.Fixes/commit/e4d7e708b7b931560fb00c6ea4f2163c8f823cdc) and copied and pasted the code in `resource/ui/classloadoutpanel.res`

Now I can use the new feature in my edit 😀

**Comment by ArmorKeik** [comment]
Well, I see I posted this issue quite some time ago, but today I'm back with one last suggestion.

Add a button to open the console from the HUD and not having to log in to a server to open it.

This would clearly work in the community version, since the workshop tries to keep it as vanilla as possible.

**Comment by valeriedesumo** [comment]
I don't need to log into a server to open my console

**Comment by ArmorKeik** [comment]
> I don't need to log into a server to open my console

You can set in the launch parameters to open the console when opening the game (-console).

Or, you can also press a key to open the console (from the keyboard configuration).

But, if you close the console when you are in the main menu, you will not be able to open it even if you press the key to open it.
This is annoying, so there are several HUDs that are already integrated with an option in the menu to open and close it.

Translated with www.DeepL.com/Translator (free version)

**Comment by Winth211** [comment]
![20220306191638_1](https://user-images.githubusercontent.com/82706197/156934146-ccfae4a7-75dc-4cc9-bac1-cecd3c272848.jpg)

Is everything even here?

P.S. It would be nice to add minimized player destruction panel

**Comment by CriticalFlaw** [comment]
> 1. But both share a bug in adding the Improved Create Server Menu. As you can see, the text of the options is not displayed, but the commands that each option executes are shown.

I believe it's best to not integrate standalone mods such as these into this project and instead have the user install the mod themselves if they want to use it. Otherwise users may report issues with the mod or argue for its removal because they find it too busy or unnecessary.

> 2. The new font mod, the Source Text Refont has errors with the position of the Spanish text and the 1360x738 aspect ratio.

Agreed. I've also noticed issues with the font change making it hard to see text in console while working on it. I've removed the mod and much like my answer in point 1, it's better to give the user the ability to install the mod if they want to use it.

**Comment by CriticalFlaw** [comment]
For how to add the RED/BLU team buttons to the loadout screen, go to `resource/ui/classloadoutpanel.res` and look for elements `RedButton` and `BlueButton`. You can just copy-paste those two into your version and it should work fine.

https://github.com/CriticalFlaw/TF2HUD.Fixes/blob/community/resource/ui/classloadoutpanel.res#L515

**Comment by CriticalFlaw** [comment]
Oops, I just saw that you figured out the RED/BLU team buttons. The only other request you have on here is the console button, but as it was pointed out there are multiple options to turn on the console already. I think that covers everything in this issue so I'll go ahead and close it now. Thank you for your requests.

Also, in the future it's better to keep individual issues separate so they are easier to tackle then try to discuss 3 different issues in one ticket. Thanks!
