### ISSUE TITLE
[REQUEST] Revert the spectator screen to the default state

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/TF2HUD.Fixes#242]
**Describe the change request.**

Reasons:
* Long killfeed overlaps respawn tIme
* Server's killstreak notification overlaps respawn time
* Boss healthbar overlaps respawn time
* Bottom text is difficult to read due to the lack of background
* Instead of disabling the bottom spectator bar correctly, its height has been reduced
* Some panels are partially outside the top spectator bar, and it looks ugly #224
* Because the bottom spectator bar was reduced it broke this #136

**Comment by CriticalFlaw** [comment]
I think I'm going to take time and regression test everything before making more changes.

**Comment by CriticalFlaw** [comment]
Fixed in 9f2652f0d612af1f7da9d5450e410f3cf0805041
