### ISSUE TITLE
Suggestion: Include Smissmas Casual Gametype Image Fix 

### ISSUE THREAD

**Issue by Sloofy** [CriticalFlaw/TF2HUD.Fixes#25]
[Smissmas Casual Gametype Image Fix](https://gamebanana.com/mods/27036) is a mod that makes it so the Smissmas gamemode banner in the casual map selection screen is consistent with all other gamemode banners. Not exactly sure if this would go under the Community edition or not.

![Example](https://images.gamebanana.com/img/ss/mods/5fc98ed25f81d.jpg)

**Comment by valeriedesumo** [comment]
If the problem was that the image ends too early, the mod now makes it end much later than all the other pictures, and with a much sharper line than the fading of the other pictures

**Comment by Sloofy** [comment]
Had to get a closer look to check, but yeah, does seem like that is the case. That's rather unfortunate. Can't really tell if this is also the case, though I noticed the mod makes the image in a lower quality than that of the original. Still, the gamemode consistency issue might be something to address in some form. Should I create a new issue for that, then?

**Comment by CriticalFlaw** [comment]
Sorry it took me so long to get to this issue. At this point the gamemode is not available so I can't really test a fix for it. You can either close this issue or keep it open until the next seasonal event. Up to you, I personally don't think it's too big of an issue.

**Comment by Winth211** [comment]
@CriticalFlaw Can you add it now so you don't forget? If there are any problems because of it, then you can roll it back later.

**Comment by CriticalFlaw** [comment]
Closing because the proposed mod is not fixing the issue it tries to address.
