### ISSUE TITLE
[BUG] Stats background disappears after opening the hud options menu

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/TF2HUD.Fixes#261]
**Describe the issue.**
Operating system - Windows 11 Enterprise 22H2
Resolution - 1920x1080

**Screenshots**
![hudoptionsbug](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/117596825/09ce0fc5-147c-4e7a-a64a-7828e0d46cc9)

**Comment by CriticalFlaw** [comment]
Its a known side effect of using the SafeMode panel. Not sure why thats tied to the stats background but given that the panel is an optional extra I don't think its a big deal
