### ISSUE TITLE
[BUG] DamagedPlayer event causes FPS drops on fast firing weapons

### ISSUE THREAD

**Issue by mtxfellen** [CriticalFlaw/TF2HUD.Fixes#263]
`event DamagedPlayer` in `hudanimations_custom.txt` currently looks like this:

```Valve-Data-Format
event DamagedPlayer
{
	Animate CustomCrosshair		FgColor     "Hitmarker"		Linear 	0.0 	0.00001
	Animate CustomCrosshair		FgColor     "Crosshair"		Linear 	0.10 	0.10001
}
```

This will cause the animation to queue up on fast firing weapons and incur potentially significant performance penalties (regardless of whether you actually use a custom crosshair or hitmarker), most easily reproducible by using the Projectile Shield in MvM.

The remedy for this is to use a guard like this, which will cancel the previous event before running the next.

```Valve-Data-Format
event DamagedPlayer
{
	StopEvent HitMarker 0.0
	RunEvent HitMarker 0.00001
}

event HitMarker
{
	Animate CustomCrosshair		FgColor     "Hitmarker"		Linear 	0.0 	0.00001
	Animate CustomCrosshair		FgColor     "Crosshair"		Linear 	0.10 	0.10001
}
```

**Comment by CriticalFlaw** [comment]
Good catch, other custom HUDs all use this.

**Comment by Kruphixx** [comment]
Tested the fix on another hud and it does seem to fix the perfomance issue as expected. No framerate drops with the shield.
