### ISSUE TITLE
[REQUEST] Make custom crosshairs visible in spectator mode

### ISSUE THREAD

**Issue by Kruphixx** [CriticalFlaw/TF2HUD.Fixes#265]
Right now the custom crosshair is not shown in spectator which looks rather odd. 

A good fix would be simply moving it to hudlayout.

**Comment by CriticalFlaw** [comment]
Moving it out of hudlayout is intentional because it doesn't make sense for the custom crosshair to be shown in spectator mode while the in-game does not.

**Comment by Kruphixx** [comment]
Why doesn't it make sense? The default crosshair is shown in spectator, the custom one should behave this way as well. It just makes no sense, right now for example you can't really tell where the person you're spectating is aiming.

**Comment by CriticalFlaw** [comment]
So if the normal crosshair does not appear when spectating in third person or freecam and even if you do spectate in first person, the hitmaker does not work - what value is there to having the HUD crosshair be shown in spectate?

**Comment by CriticalFlaw** [comment]
Closing per comment above. Thank you for the suggestion.
