### ISSUE TITLE
[BUG] Custom crosshair color resets to white after hitmarker animation ends

### ISSUE THREAD

**Issue by Kruphixx** [CriticalFlaw/TF2HUD.Fixes#266]
Title. I have a short video showing the issue:

https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/50501742/cd6b5642-1b0e-44c6-adcb-0fb90795765d

As you can see, I change the color of the crosshair to green but it resets to white anyway when the hitmarker animation ends. Clearly not intended behavior.

**Comment by CriticalFlaw** [comment]
Fixed in 916980e2901fc54b370326d31225586cd48452bc. It was an oversight where the crosshair color should have been set in the clientscheme. This also does mean that you have to restart the game for the color change to take effect.
