### ISSUE TITLE
[BUG] The preview in the Decal Tool menu is not displayed

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/TF2HUD.Fixes#269]
This issue does not occur in the Default HUD

**Comment by CriticalFlaw** [comment]
I think this may be tied to changes in either to either `resource/ui/econ/inspectionpanel.res` or `.../itemmodelpanel.res` since they modify how the item appears and maybe the decal panel feeds off it?

**Comment by CriticalFlaw** [comment]
Turns out its caused by https://github.com/CriticalFlaw/TF2HUD.Fixes/blob/main/resource/ui/econ/backpackpanel.res#L125 where inventory_image_type = 1. This is used to have sharper quality item images be used in the backpack at I guess the cost of it not showing on the preview of the decal tool
