### ISSUE TITLE
Persistent menu_thumb_missing error

### ISSUE THREAD

**Issue by Tiagoquix** [CriticalFlaw/TF2HUD.Fixes#27]
In the readme file it states that the "menu_thumb_Missing" console error is fixed. But how?
No files have been added or modified within the materials folder.

If the fix is indeed present, could you implement it in FlawHUD as well?

Thanks in advance.

**Comment by Tiagoquix** [comment]
Also, the Steam Workshop Submission description is outdated when compared to the description on GitHub.

**Comment by Winth211** [comment]
@Tiagoquix [Revert fix to console error for menu_thumb_Missing](https://github.com/CriticalFlaw/TF2HUD.Fixes/commit/fcf1ab7ec588aee80574c899b33ef80e5fe01292)

**Comment by Tiagoquix** [comment]
> @Tiagoquix [Revert fix to console error for menu_thumb_Missing](https://github.com/CriticalFlaw/TF2HUD.Fixes/commit/fcf1ab7ec588aee80574c899b33ef80e5fe01292)

Yes but: https://github.com/CriticalFlaw/TF2HUD.Fixes#changes-include

> Fixed console errors related to missing files menu_thumb_missing and huditemeffectmeter_action.

**Comment by CriticalFlaw** [comment]
I'm going to take the time to look into this again and see if it can actually be fixed. If not, then I'll pull the change and update the text accordingly. Thanks.

**Comment by Winth211** [comment]
P.S. Remove duplicate in README.md


![Снимок экрана 2022-03-09 090142](https://user-images.githubusercontent.com/82706197/157389607-3dcb633d-31ed-4442-8231-992baed07324.png)

**Comment by Winth211** [comment]
Maybe i'm blind, but after some changes menu_thumb_missing error is stop appear

![image](https://user-images.githubusercontent.com/82706197/159072302-0725d020-ceee-4968-baf1-ce25418c9ad5.png)
![image](https://user-images.githubusercontent.com/82706197/159072381-d6c1fd69-7fc7-4c1d-aa07-bb1d93478662.png)

**Comment by CriticalFlaw** [comment]
hmmm maybe you did fix it. I'd conduct a test with clear steps to reproduce the error before and after your changes to verify.

**Comment by CriticalFlaw** [comment]
I did some testing and here are my findings.

To fix the console error, you need the `menu_thumb_Missing.vmt` file in `materials/vgui/maps` folder. Doing so fixes the error and you can easily test by going to a server, picking a class and checking the console.

However this only works on local, once you join an official server the file will no longer be detected and the console error will return. That is what happened when initially and got me to pull change entirely. To fix this issue proper, the file will need to be preloaded much like how its done for custom control point icons in other custom huds.

In the `workshop` branch there should be no need for preloading so long as Valve adds the missing file to the correct directory on their side.

**Comment by CriticalFlaw** [comment]
Fixed in https://github.com/CriticalFlaw/TF2HUD.Fixes/commit/f07a9a7a1cd2a5c85cc7bb0df90719d788eb80c8

**Comment by Tiagoquix** [comment]
@CriticalFlaw Please include this fix in FlawHUD as well.

**Comment by Winth211** [comment]
@CriticalFlaw Port this fix to FlawHUD and RaysHUD
