### ISSUE TITLE
[BUG] Arena player count and respawn label overlap a bit

### ISSUE THREAD

**Issue by Kruphixx** [CriticalFlaw/TF2HUD.Fixes#272]
Resolution: 1920x1080
Operating system: Windows 11

![20240418131919_1](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/50501742/66450279-e16a-48d9-941e-d92c07cb42f0)

**Comment by CriticalFlaw** [comment]
Is this happening with the default HUD as well? I recall they lowered the arena player count in that as well

**Comment by Kruphixx** [comment]
It does happen on the default HUD yeah

![20240419100332_1](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/50501742/d596dc00-1c33-46a2-88ba-0f7e50e50df7)

**Comment by CriticalFlaw** [comment]
The only way to fix this is to move it up or reduce the size of those panels. Probably the former

**Comment by CriticalFlaw** [comment]
Fixed in 7e6007dfdb2a2320166cec3055eab5e121c3a9f2

![20240420224527_1](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/6818236/4d170f07-20b0-4115-82d5-8ee5c724308b)

**Comment by Kruphixx** [comment]
@CriticalFlaw The reason it was in that position is because then it wouldn't overlap with the setup label, now it kinda will. Look here:

https://steamcommunity.com/sharedfiles/filedetails/?id=3049413665

**Comment by CriticalFlaw** [comment]
> @CriticalFlaw The reason it was in that position is because then it wouldn't overlap with the setup label, now it kinda will. Look here:
> 
> https://steamcommunity.com/sharedfiles/filedetails/?id=3049413665

Thanks. Oddly the "Setup" label did not show up during my testing but I revised the fix by lowering the respawn countdown instead.

![20240421094024_1](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/6818236/3c175b58-a8ae-43f0-89f0-38444f5e0769)
