### ISSUE TITLE
[BUG] Overtime text overlaps the server map timer

### ISSUE THREAD

**Issue by kittenchilly** [CriticalFlaw/tf2hud.fixes#273]
**Describe the issue.**
If any server has the map timer, whenever it goes into overtime the text overlaps the timer. This doesn't happen with other text like the Setup text.

**Screenshots**
![20240422204158_1](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/23617175/6cf8c24d-bbcc-4d0a-8f32-ba4a42bd9175)

**Comment by CriticalFlaw** [comment]
Fixed in https://github.com/CriticalFlaw/tf2hud.fixes/pull/278 by @Kruphixx
