### ISSUE TITLE
[BUG] Canteen charges overlap stored crits/heads panel

### ISSUE THREAD

**Issue by Whurrhurr** [CriticalFlaw/TF2HUD.Fixes#274]
**Screenshots**
frontier justice, diamondback:
![image](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/33162051/41c7b0d2-4157-431f-92ca-0a2e704e9821)

eyelander/bazaar bargain:
![image](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/33162051/3fd54ae4-58b2-4c2b-81ef-08b219ddcb55)

**Comment by CriticalFlaw** [comment]
Fixed in 68b8cfd64b5014330aae8eb28422cd68a37abd9c. This was apparently already fixed in the workshop version so it was just backpoirted
