### ISSUE TITLE
[REQUEST] Remove obsolete line modifiers & tags (e.g _hidef, _lodef, [$X360] from project files

### ISSUE THREAD

**Issue by Kruphixx** [CriticalFlaw/tf2hud.fixes#279]
![Screenshot 2024-06-06 122331](https://github.com/CriticalFlaw/tf2hud.fixes/assets/50501742/6efd84c3-0a28-43c2-8b24-cd03d13dce5b)

All of these are only for XBOX and don't do anything on PC, might be better to just remove them. Will also make files look a bit cleaner I suppose?

I think it'd be good if they were removed from all currently modified .res files. I'm up for the challenge if that's something you want done @CriticalFlaw.

**Comment by CriticalFlaw** [comment]
I like the idea but I feel like it doesn't fit the scope of this project for a few reasons:

1. Majority of the HUD files that are not modified by this mod will still have these tags
2. It adds additional effort for when I have to create a workshop version that excludes certain changes
3. It does not impact the player experience whether the tags are there or not

I think it's a good idea to submit a separate workshop item specifically to remove those extraneous tags. Maybe even create a script that will remove them for you, run it against the default HUD files then publish the results to the workshop.

**Comment by Kruphixx** [comment]
Fair enough I suppose, as I said it's mostly to make files look cleaner since some of them are a bit of a mess with all the unneeded tags.

As for your first point though, isn't that already the case anyway? Newer files don't have those tags.
