### ISSUE TITLE
[BUG] Scoreboard is too big for 1280 x 1024 resolution.

### ISSUE THREAD

**Issue by Pikasatupu75** [CriticalFlaw/tf2hud.fixes#281]
**Describe the issue.**
Scoreboard is too big for my screen. I can't properly see the badges of the players on the left side of the screen and can't see the ping of players on the right side of the screen. My screen resolution is 1280 x 1024, 4:3.

**Screenshots**
![20240727193957_1](https://github.com/user-attachments/assets/33faf48a-0b4d-4ddb-9399-65de6501f726)

**Comment by Kruphixx** [comment]
I'm not CriticalFlaw but I'm just gonna give my own thought here, I don't think much can be done here? Pretty sure 1280x1024 is actually 5:4, not 4:3, which is a resolution most games don't like.

**Comment by Pikasatupu75** [comment]
There isn't 5:4 in settings. If it is relevant, I am using the windowed mode in fullscreen.
![20240727203824_1](https://github.com/user-attachments/assets/d3919b37-5818-4c0c-a8aa-267aaf396e54)

**Comment by Rorriis** [comment]
Most source games ( But not HL2 for some reason? ) group 5:4 with 4:3
Most of the options are 4:3, but there are two 5:4 options: 720x576 and 1280x1024

Left 4 Dead 2
![Screenshot_20240803_124537](https://github.com/user-attachments/assets/619460e3-820c-4e72-9644-dfecd1bedcda)
Day of Defeat Source
![Screenshot_20240803_124721](https://github.com/user-attachments/assets/3adb69ad-2ef0-4477-92d8-fe8f407a05ae)

**Comment by CriticalFlaw** [comment]
The TF2 scoreboard is not meant to dynamically scale to lower resolutions. Unfortunately this is also something that cannot be fixed through HUD files without redesigning the entire scoreboard, which would be out of scope for this mod.
