### ISSUE TITLE
[BUG] Badge in main menu is misaligned.

### ISSUE THREAD

**Issue by Pikasatupu75** [CriticalFlaw/tf2hud.fixes#282]
**Describe the issue.**
Badge in main menu is misaligned. Clicking on where it is supposed to be makes it flip and creates sparks. Competitive badge has the same issue too. My screen resolution: 1280 x 1024, 4:3.
**Screenshots**
![20240727195200_1](https://github.com/user-attachments/assets/153b7c08-857b-4e3d-9eca-de86492232da)

**Comment by CriticalFlaw** [comment]
Fixed in 8c32405e9e6c2188d9eb0e0e298a4ea9a5c3e2bf. Thanks
