### ISSUE TITLE
[BUG] Killstreak count overlaps with killstreak indicator.

### ISSUE THREAD

**Issue by Pikasatupu75** [CriticalFlaw/tf2hud.fixes#283]
**Describe the issue.**
If you are looking at someone with a killstreak while dead or alive, the killstreak indicator and count overlaps making it almost impossible to read. My screen resolution: 1280 x 1024, 4:3.

**Screenshots**
![20240727200532_1](https://github.com/user-attachments/assets/dab43319-f4fb-4651-96da-b5c2bfde6830)
![20240727200554_1](https://github.com/user-attachments/assets/42f4a8a8-cf1a-4a51-be2e-001fe297ae60)

**Comment by CriticalFlaw** [comment]
I wasn't able to reproduce the issue on my side, though I have seen it at times before. I would suggest refreshing the HUD once using the `hud_reloadscheme` command next time you encounter this problem and see if it persists.

![20240815215049_1](https://github.com/user-attachments/assets/e44e3463-b799-4fcc-9c41-45d946de9158)
