### ISSUE TITLE
[BUG] Team Colors Paint don't work

### ISSUE THREAD

**Issue by DRAG4YOU** [CriticalFlaw/tf2hud.fixes#284]
If you have team colored painted hat or cosmetic the paint only works correctly on Red but not on Blu.

![snapshot0026](https://github.com/user-attachments/assets/65f2fd45-35a3-416a-ae01-060849aaac0e)
![snapshot0027](https://github.com/user-attachments/assets/d1ad131a-aa58-4eb4-9258-121844c2508c)

**Comment by Rorriis** [comment]
Not sure much can be done for this, since its a bug with the r_skin command, unless Valve fixes it

**Comment by CriticalFlaw** [comment]
Like Rorriis said, this is a game bug that can't be fixed with HUD files.
