### ISSUE TITLE
Vita-saw counter bug

### ISSUE THREAD

**Issue by Winth211** [CriticalFlaw/TF2HUD.Fixes#30]
![20220315113254_1](https://user-images.githubusercontent.com/82706197/158348880-36b77c5a-e84b-4040-ba8a-11de65bccf1e.jpg)
![20220314203903_1](https://user-images.githubusercontent.com/82706197/158348887-bdb7bd98-ff57-4a8b-8e49-ae0d404560c5.jpg)

**Comment by ArmorKeik** [comment]
Here I attach another image.
I use a modified version of the "community".

![image](https://user-images.githubusercontent.com/87909542/158633970-172a9c48-a9ed-4326-80d8-4e3348286512.png)

**Comment by CriticalFlaw** [comment]
I'm working on redoing the panels in the backend for consistency. Will push the change to the community branch once ready. Thanks.

**Comment by CriticalFlaw** [comment]
I'll push this and few other changes to the `community` branch tomorrow.

**Comment by CriticalFlaw** [comment]
Fixed in https://github.com/CriticalFlaw/TF2HUD.Fixes/commit/8eb94ca9c34001c80bcd5d30abbedc4ed7b32417
