### ISSUE TITLE
SpectatorGuiHealth is cutoff in multiple places.

### ISSUE THREAD

**Issue by Winth211** [CriticalFlaw/TF2HUD.Fixes#31]
![20220318181523_1](https://user-images.githubusercontent.com/82706197/159041531-46535856-79f2-469f-839b-adeb32aaa905.jpg)
![20220318181825_1](https://user-images.githubusercontent.com/82706197/159041706-3e2e7a18-8324-43f7-95af-756bd822cfec.jpg)
![20220318181800_1](https://user-images.githubusercontent.com/82706197/159041711-9c636d1b-ddfd-4dd5-b50e-89832fcbbb80.jpg)
![20220318184005_1](https://user-images.githubusercontent.com/82706197/159045407-969237c5-0821-4bd6-a6c0-cd5ebb75b1ce.jpg)

**Comment by Winth211** [comment]
Target hp cut a bit

**Comment by CriticalFlaw** [comment]
Oops, missed that one when I was merging them back in. Will push a fix shortly. Thanks

**Comment by CriticalFlaw** [comment]
Reopening to address other occurrences of this issue.

Target HP still cut in spy panel(min mode)
![20220319171214_1](https://user-images.githubusercontent.com/82706197/159128117-43bf2942-8dd2-4272-b232-a354df36205d.jpg)

Overheal cross still not centered or this is suppose to be?
![20220319171757_1](https://user-images.githubusercontent.com/82706197/159128119-7a0606b7-26a8-4227-a6a6-3a19674665da.jpg)
![20220319171841_1](https://user-images.githubusercontent.com/82706197/159128121-beddc57a-5bf9-4abe-9d70-1d614addf354.jpg)

Killer target id still has default hp icon:
![1](https://user-images.githubusercontent.com/82706197/159128139-176b3f4c-d9e8-4e9c-9146-d835d310f002.png)

**Comment by Winth211** [comment]
![20220320082202_1](https://user-images.githubusercontent.com/82706197/159150834-b76162fa-9172-4e6e-b3aa-29cc831c30de.jpg)
![20220320082231_1](https://user-images.githubusercontent.com/82706197/159150835-e5befda4-e10d-4cc6-b8cb-1b8e16467762.jpg)

**Comment by CriticalFlaw** [comment]
Oops forgot to commit the rest of this change. Done now.

**Comment by Winth211** [comment]
@CriticalFlaw Player's health is white (left corner) + target's health does not change when he is overhealed 
![20220320192016_1](https://user-images.githubusercontent.com/82706197/159175100-f97d2a13-c588-4f3d-bd67-8033a3af5c73.jpg)
