### ISSUE TITLE
Change the fallback Windows font used in Linux

### ISSUE THREAD

**Issue by quickkennedy** [CriticalFlaw/TF2HUD.Fixes#32]
these are a few things id like to see out of this hud. i did make my own fork, but realized i could probably improve this hud by recommending the changes here rather than making my own changes.

1. currently on windows (but not linux) the console font appears pixelated. this could be fixed by editing the "sourceshemebase" file from the platform vpk by adding the antialias property to a font or two. as far as i know, this doesn't cause any issues and just looks better on windows.
2. id recommend is  you to move all your customizations to a customizations folder, as it always looks neater. i think you've already done this with crosshairs (although im not so sure how you would enable them with the file in the "extras" folder), but transparent viewmodels would also be nice to see there.
3. i think you should also add a customization that lets people turn the damageaccount on or off, as im sure some users would be distracted by the number in the bottom right of their screen.

i would have also said to add keys to use for navigation, however you've already done that an hour ago. thanks for that.

**Comment by Winth211** [comment]
I will also add something:

There is strange visual glitch when on loading panel appear white dots along the edges, same happening with console sometimes.
![1](https://user-images.githubusercontent.com/82706197/159058609-8e2f3a72-0685-4ba2-a02f-54179e2da9fd.png)


It would be cool if in main menu you can see your statistic like in some custom huds.
![530-90_60e375446082c](https://user-images.githubusercontent.com/82706197/159059337-caad7de5-dca2-448c-9e71-b96f98347bf6.jpg)

**Comment by CriticalFlaw** [comment]
@Winth211 Please create a separate issue ticket for these. It makes it easier for me to manage these requests if they are separate and not bundled together, unless they have some commonality.

**Comment by CriticalFlaw** [comment]
> 1. currently on windows (but not linux) the console font appears pixelated. this could be fixed by editing the "sourceshemebase" file from the platform vpk by adding the antialias property to a font or two. as far as i know, this doesn't cause any issues and just looks better on windows.

I like the idea, but I don't have a Linux machine set up to test this. If you or someone can create a PR and provide screenshots of the before/after as proof that would be great.

> 2. id recommend is you to move all your customizations to a customizations folder, as it always looks neater. i think you've already done this with crosshairs (although im not so sure how you would enable them with the file in the "extras" folder), but transparent viewmodels would also be nice to see there.

Yeah, I started thinking of doing that for most other customizations but stopped at crosshairs because I remembered that I would also need to update the editor schema for this to work. This will definitely be revisited and refined.

> 3. i think you should also add a customization that lets people turn the damageaccount on or off, as im sure some users would be distracted by the number in the bottom right of their screen.

I don't see any issues with offering that as a customization option. Would make it easy to implement in the editor too once number 2 above is addressed.

**Comment by quickkennedy** [comment]
> > 1. currently on windows (but not linux) the console font appears pixelated. this could be fixed by editing the "sourceshemebase" file from the platform vpk by adding the antialias property to a font or two. as far as i know, this doesn't cause any issues and just looks better on windows.
> 
> I like the idea, but I don't have a Linux machine set up to test this. If you or someone can create a PR and provide screenshots of the before/after as proof that would be great.

sorry, this isnt anything linux specific, i was just adding that in case you used linux. if you used linux you wouldnt be able to see the problem. its not a bug, i just mean that the console font should have the antialias property.

**Comment by CriticalFlaw** [comment]
My apologies, I badly misread what you had written. IF you have a fix for this issue, could you please create a PR with comparison screenshots?

**Comment by unsubtract** [comment]
My understanding is that the Windows console font is intentional (it even appears in 2004 builds of Half-Life 2 and GoldSrc games), and the Linux one is broken. Linux appears to fall back to the system-default sans-serif font, while Windows uses the correct console font (which is monospaced).

**Comment by CriticalFlaw** [comment]
> My understanding is that the Windows console font is intentional (it even appears in 2004 builds of Half-Life 2 and GoldSrc games), and the Linux one is broken. Linux appears to fall back to the system-default sans-serif font, while Windows uses the correct console font (which is monospaced).
> 
> Linux fonts in general tend to behave strangely with Source, and you can only fix them by bundling the fonts with the HUD (they're system fonts on Windows but not any Linux distros).

If someone could try this suggestion out and test on Linux, I'd happily add it through a PR. I don't have a Linux build handy to try this myself.

**Comment by hkva** [comment]
> My understanding is that the Windows console font is intentional (it even appears in 2004 builds of Half-Life 2 and GoldSrc games), and the Linux one is broken. Linux appears to fall back to the system-default sans-serif font, while Windows uses the correct console font (which is monospaced).

> Linux fonts in general tend to behave strangely with Source, and you can only fix them by bundling the fonts with the HUD (they're system fonts on Windows but not any Linux distros).

I don't think this can be fixed. Microsoft fonts have very strict redistribution rules (https://docs.microsoft.com/en-us/typography/fonts/font-faq). This is why many Linux distros don't supply these fonts and packaging them with the hud would violate copyright law.

**Comment by CriticalFlaw** [comment]
As pointed out by @hkva - bundling Windows fonts with the HUD is not allowed per Microsoft and therefore cannot be added. Hopefully this is something Valve themselves can mitigate in lieu of using another Source-compatible font entirely.

![image](https://user-images.githubusercontent.com/6818236/179045211-5c932a14-cdf7-4b88-b4bd-2bbbdb2f4e2e.png)
