### ISSUE TITLE
Request to add stats to the main menu

### ISSUE THREAD

**Issue by Winth211** [CriticalFlaw/TF2HUD.Fixes#33]
It would be cool if in main menu you can see your statistic like in some custom huds.
![530-90_60e375446082c](https://user-images.githubusercontent.com/82706197/159059337-caad7de5-dca2-448c-9e71-b96f98347bf6.jpg)

**Comment by CriticalFlaw** [comment]
I think the corners are a source engine issue. Don't think it can be fixed through HUD files.

The stats are a cool idea. Is there a mod of this that can be added with the author's permission?

**Comment by Winth211** [comment]
@CriticalFlaw  https://gamebanana.com/mods/302031

**Comment by Winth211** [comment]
> I think the corners are a source engine issue. Don't think it can be fixed through HUD files.

Actually, you can make both loading panel and console square, this is should fix white corners glitch.

**Comment by CriticalFlaw** [comment]
Oh right. I think some custom huds, do that. If you can open a PR for that, that'd be great

**Comment by CriticalFlaw** [comment]
Added in https://github.com/CriticalFlaw/TF2HUD.Fixes/commit/d79a0b356cb3004ba88048d353f80b7c06ded45f thanks to @Jofre-Problem who has been credited accordingly.
