### ISSUE TITLE
Request to change form of loading panel and console to square

### ISSUE THREAD

**Issue by Winth211** [CriticalFlaw/TF2HUD.Fixes#34]
There is strange visual glitch when on loading panel appear white dots along the corners, same happening with console sometimes. This can be fixed by making the loading bar and console square via the sourcescheme.  Some custom hud already have this feature.

![image](https://user-images.githubusercontent.com/82706197/159090159-3d166bfa-70bd-4973-810a-cbb175f3c448.png)

Optimized Default HUD
https://gamebanana.com/mods/177271

![image](https://user-images.githubusercontent.com/82706197/159118971-03051e64-311b-4fbd-9e5a-9a77413c4975.png)

**Comment by Winth211** [comment]
@CriticalFlaw Everything works now!
![image](https://user-images.githubusercontent.com/82706197/159138050-6c5ec1d1-ba39-4d09-87c5-0d4f7cf54044.png)
![image](https://user-images.githubusercontent.com/82706197/159138079-3c821c6e-fe49-427f-9bd5-7b9c23193eae.png)

**Comment by CriticalFlaw** [comment]
Does it work on the loading screen panel?

**Comment by CriticalFlaw** [comment]
Added in https://github.com/CriticalFlaw/TF2HUD.Fixes/commit/1dee7483397123e88636278111f71c45d495ee54
