### ISSUE TITLE
Add minmode variants to all gamemode specific panels.

### ISSUE THREAD

**Issue by Winth211** [CriticalFlaw/TF2HUD.Fixes#35]
Same with ctf min mode, it would be nice to add min mode of player destruction panel. 
![20220319092813_1](https://user-images.githubusercontent.com/82706197/159112422-59cef4ef-17a2-4ac7-8f45-94975e2527e0.jpg)

 I think some elements of the ctf panel are not quite evenly placed to each other (right side is longer than left side and blu briefcase farther than red briefcase)
![20220319091934_1](https://user-images.githubusercontent.com/82706197/159112745-ba1fa03f-4bb3-4531-abd5-452d0319f908.jpg)

**Comment by Winth211** [comment]
+ I think, or some elements of the panel are not quite evenly placed 
![20220319091934_1](https://user-images.githubusercontent.com/82706197/159112745-ba1fa03f-4bb3-4531-abd5-452d0319f908.jpg)

**Comment by CriticalFlaw** [comment]
Added in https://github.com/CriticalFlaw/TF2HUD.Fixes/commit/02ca2666b25e5447e65a32078ecef2c3cb1856b4
