### ISSUE TITLE
Bomb icon is misaligned in Mann vs. Machines.

### ISSUE THREAD

**Issue by Winth211** [CriticalFlaw/TF2HUD.Fixes#37]
Bomb icon not fully in circle:
![20220319161532_1](https://user-images.githubusercontent.com/82706197/159128116-eb1ac3dd-62e0-4fb6-bbb9-18027a1523e1.jpg)

**Comment by CriticalFlaw** [comment]
Hi. I moved some of the issues reported here to #31 because it makes no sense to keep creating new issues for the same issue. I'd also like to keep issues separate instead of bundling multiple in one. Thanks

**Comment by CriticalFlaw** [comment]
Does the bomb icon correct itself after you refresh the HUD via `hud_reloadscheme` in console?

**Comment by Winth211** [comment]
@CriticalFlaw I haven't tried hud_reloadscheme, but I don't think that will help.

**Comment by CriticalFlaw** [comment]
It might, certain elements get corrected after `hud_reloadscheme` so give that a try and let me know.

**Comment by Winth211** [comment]
![20220319214904_1](https://user-images.githubusercontent.com/82706197/159136288-31fdb082-b4e6-4982-98a0-b76e428edbf3.jpg)
![20220319214901_1](https://user-images.githubusercontent.com/82706197/159136289-86818b4d-39f6-4ebe-9b31-1cebff7f5bd0.jpg)

**Comment by CriticalFlaw** [comment]
Fixed in https://github.com/CriticalFlaw/TF2HUD.Fixes/commit/55692ce3bca55f4746ae6e7b6c64628b2b21f6b6
