### ISSUE TITLE
HP numbers bug

### ISSUE THREAD

**Issue by Winth211** [CriticalFlaw/TF2HUD.Fixes#38]
The player's health turns white when overhealed, but the target health does not indicate when it is overhealed (overhealing cross or color change). 

![20220321102019_1](https://user-images.githubusercontent.com/82706197/159226074-6559f755-81dd-4f80-8a15-57b07bdd9c16.jpg)
![20220321102001_1](https://user-images.githubusercontent.com/82706197/159226079-11cfa67a-61a8-4d9a-837f-adebd7d5bfbc.jpg)
![20220321134858_1](https://user-images.githubusercontent.com/82706197/159255862-bd625c35-7c75-4760-873f-9c97c2b8081f.jpg)

**Comment by CriticalFlaw** [comment]
Oh, right. The number value in the targetID and player health share the same variable name. So that just needs to be changed.

The targetID will not show a cross anymore due to limited space, I'm looking into displaying an icon or change the health to a color that is easily visible.
