### ISSUE TITLE
Tournament spectator and freeze panel use the old health style

### ISSUE THREAD

**Issue by Winth211** [CriticalFlaw/TF2HUD.Fixes#40]
![22](https://user-images.githubusercontent.com/82706197/159459177-13e29bf0-708b-4990-b3ff-9e4c3e66f891.png)
![20220321220917_1](https://user-images.githubusercontent.com/82706197/159459437-55c0f620-3594-4cdb-a5f4-4eabe7d81da6.jpg)
![20220321221411_1](https://user-images.githubusercontent.com/82706197/159459441-ab656008-7944-4937-9db0-eb51c3943ffe.jpg)

In min mode, freezecam shows standard health cross, not the minimized one. The kill streak icon sometimes blends in with kill count. (workshop)

**Comment by CriticalFlaw** [comment]
![image](https://user-images.githubusercontent.com/6818236/160967225-9970a079-dbef-445c-9258-869c526015e1.png)
