### ISSUE TITLE
level progress bar disappeared

### ISSUE THREAD

**Issue by Blueberryy** [CriticalFlaw/TF2HUD.Fixes#43]
i'm using latest version of TF2HUD.Fixes (v2022.0331) and for some reason i see this after round end...
![image](https://user-images.githubusercontent.com/36592509/161159222-05c39ba7-51c9-4197-b5a4-a8cf8558f98d.png)

**Comment by CriticalFlaw** [comment]
Must have been changes to pvprankpanel to get the matchmaking stats to display on the main menu. `if_mini` values in pvprankpanel.res would need to be updated to fix this.
