### ISSUE TITLE
Advanced Options background is transparent

### ISSUE THREAD

**Issue by TeaEffTeu** [CriticalFlaw/TF2HUD.Fixes#44]
The background for the advanced options menu is transparent which makes it difficult to read anything.

![image](https://user-images.githubusercontent.com/61724664/161169896-a594c07b-6fab-499b-acde-e9c05d768496.png)

**Comment by CriticalFlaw** [comment]
Fixed in https://github.com/CriticalFlaw/TF2HUD.Fixes/commit/693132ae72a1991e23ee2342a4388c95ffbdbaaa. Thanks!
