### ISSUE TITLE
"... is carrying" textbox covers spectator information

### ISSUE THREAD

**Issue by Sloofy** [CriticalFlaw/TF2HUD.Fixes#48]
### Issue
When in spectator view, if targeting a person who has an inspectable weapon, the textbox will cover the map information and the prompt to change class. Moving it further up would probably help.

### Specifications
Fedora Linux 35
Using the community branch up to the April 3rd, 2022 version
Playing at 1920x1080

### Screenshot
![Is carrying](https://user-images.githubusercontent.com/18003771/162278551-8912c997-4064-4284-818e-d8d35c01e6b9.png)

**Comment by CriticalFlaw** [comment]
Fixed in #55 by @Sloofy
