### ISSUE TITLE
Request to make overhealed targets visibly more distinct

### ISSUE THREAD

**Issue by Sloofy** [CriticalFlaw/TF2HUD.Fixes#51]
### Issue
When a person has overheal, there is no visual indication they are exceeding their normal healthpool. This makes identifying people who aren't overhealed difficult, especially when they're a Medic in a choke point. By making the person's health green once they've been overhealed, it would improve readability and provide immediate feedback during heavy combat.

### Screenshot
![Screenshot_20220408_163743](https://user-images.githubusercontent.com/18003771/162547076-bd646cf7-0ad6-4024-be73-b7b7578e6c57.png)

**Comment by Ashetf2** [comment]
The change is missing for target health.
![image](https://user-images.githubusercontent.com/63692647/182042602-4d3901e7-360c-48de-847a-2c315ea9b287.png)
