### ISSUE TITLE
"Advanced Options" without background on linux

### ISSUE THREAD

**Issue by poloide21** [CriticalFlaw/TF2HUD.Fixes#52]
As the title says
I use 1440x900 as my resolution
![20220408235314_1](https://user-images.githubusercontent.com/103301112/162557076-e21f40ee-7a89-4706-8ec1-c4310017278f.jpg)

**Comment by CriticalFlaw** [comment]
Please download the latest version, this has already been fixed.

**Comment by poloide21** [comment]
Thanks
