### ISSUE TITLE
Shop / replay back button is not consistent with item button

### ISSUE THREAD

**Issue by Sloofy** [CriticalFlaw/TF2HUD.Fixes#53]
### Issue
When accessing the Mann Co. Store, the back button to leave the store does not align with the items button. This is unlike the behaviour shown in the items menu, which has its positioned corrected to match.

### Specifications
Fedora Linux 35
Using the community branch up to the April 3rd, 2022 version
Playing at 1920x1080

### Screenshot
![Store](https://user-images.githubusercontent.com/18003771/162600913-99ea1ffc-6fc1-42c3-9f21-ce03fcfdb031.png)

**Comment by Sloofy** [comment]
This issue also affects the replay menu as well.

**Comment by CriticalFlaw** [comment]
Addressed in 33a8df27bcd0a71b20983f12a1238898f23e64ea
