### ISSUE TITLE
Back button in the items menu is shorter than the items button

### ISSUE THREAD

**Issue by Sloofy** [CriticalFlaw/TF2HUD.Fixes#54]
### Issue
This one is really nitpicky, but might as well since it's trying to be consistent with the button before it.

On the main menu, when navigating into the items menu, the back button replacing the items button is actually shorter than it should be. In the screenshot below, the lines should be intersecting with each other (the left is the main menu, the right is the items menu which replaces the button). You may have to zoom in to see it here, but it's fairly noticeable once you become aware of it in-game.

### Specifications
Fedora Linux 35
Using the community branch up to the April 3rd, 2022 version
Playing at 1920x1080

### Screenshot
![Super tiny nitpick](https://user-images.githubusercontent.com/18003771/162601104-cba3bc2e-2d17-4333-97c9-9478e1ec3e42.png)

**Comment by CriticalFlaw** [comment]
Addressed in 33a8df27bcd0a71b20983f12a1238898f23e64ea
