### ISSUE TITLE
Degroot Keep's capture point timer can be misaligned

### ISSUE THREAD

**Issue by kittenchilly** [CriticalFlaw/TF2HUD.Fixes#56]
The timer that appears when you capture point A and C, and the gate to point C opens can appear misaligned like this
![20220415135928_1](https://user-images.githubusercontent.com/23617175/163621878-24f2832d-c3c8-45a2-96fa-a7fca1d9d09b.jpg)
This seems to only happen if you die while it's there, other times it appears fine.
There may be other maps that this happens on but Degroot Keep was the most obvious one I could find

**Comment by CriticalFlaw** [comment]
I recall seeing this in custom huds as well, because you're not able to manually fix the position of the timer. Does it correct itself if you input `hud_reloadscheme` into console? If so, then it's likely a game bug.

**Comment by CriticalFlaw** [comment]
Just checked. This is a game issue can be corrected by using `hud_reloadscheme` - making the change in the hud files would not fix this. Closing.
