### ISSUE TITLE
Prompt to pick up buildings is broken while spectating

### ISSUE THREAD

**Issue by Sloofy** [CriticalFlaw/TF2HUD.Fixes#57]
### Issue
While spectating your own fully constructed buildings, the prompt to pick them up will be off to the side and broken.

### Specifications
Fedora Linux 35
Using the community branch up to the April 3rd, 2022 version
Playing at 1920x1080

### Screenshot
![Building](https://user-images.githubusercontent.com/18003771/163663815-cd6790dc-f3a1-4420-8c9d-805565c81ecb.png)

**Comment by CriticalFlaw** [comment]
Is this prompt corrected when entering `hud_reloadscheme` into console?

**Comment by Sloofy** [comment]
> Is this prompt corrected when entering `hud_reloadscheme` into console?

This issue persists even when using `hud_reloadscheme` in the console.

**Comment by SharpForms** [comment]
this bug is not only on linux, it's more like the bugs of tf2 itself

**Comment by CriticalFlaw** [comment]
Can confirm that this happens in Windows as well when spectating your own buildings. This isn't caused by the pack as this is happening on the default as well.

**Comment by CriticalFlaw** [comment]
After tinkering with it for a while, I wasn't able to find a way to fix it. Based on the placement of the elements, I suspect that elements within `MoveableSubPanel` were meant to be made hidden when the targetId is visible from the perspective of a spectator. I think the ideal way to fix it would be through the game code.

Perhaps it can be a new tickets on their issue tracker: https://github.com/ValveSoftware/Source-1-Games/issues

**Comment by CriticalFlaw** [comment]
Opened a ticket on the Source 1 tracker here: https://github.com/ValveSoftware/Source-1-Games/issues/4155
