### ISSUE TITLE
Change the new ammo style and new player health to the original style. Remove the matchmaking stats and change the 4 button layout from main menu to default layout.

### ISSUE THREAD

**Issue by Kamergaming15** [CriticalFlaw/TF2HUD.Fixes#58]
I actually hate that you change ammo style and player health style to more like flawhud. Why you change it? It not fit for using tf2 build font in tf2 default hud. For matchmaking stats thought, no one want that. For sure there is many player always ignore stats. And for 4 button that was right side it a same layout from flawhud. Are you trying to merge default hud and flawhud?

**Comment by Kamergaming15** [comment]
forget there is a workshop ver

**Comment by CriticalFlaw** [comment]
thank you, come again.
