### ISSUE TITLE
[BUG] Stats overview does not align with back button

### ISSUE THREAD

**Issue by Sloofy** [CriticalFlaw/TF2HUD.Fixes#61]
**Issue**
This is in-line with the previous bug report (#60) with the same issue, but instead for the stats screen (and how it isn't aligned with the back button). The purple line below should align with both elements.

**Steps to Reproduce**
1. Go to stats overview screen (from backpack or Mann Co. catalogue)
2. Observe results

**Specifications**
Latest Community branch as of April 24th, 2022
Fedora Linux KDE 35
English-CA
1920x1080

**Screenshots**
![screenie2](https://user-images.githubusercontent.com/18003771/164989612-4d581557-2236-411f-8343-dfac39f891b0.png)

**Comment by CriticalFlaw** [comment]
Could you please merge the other, similar issue with this one and track all main menu misalignments in this issue.

They're all similar in nature so I'd rather keep one master list than open multiple separate tickets. Thanks!

**Comment by CriticalFlaw** [comment]
Addressed in 2416630f45e6db8d6e75b27aeff028aafaa8fbf7

**Comment by CriticalFlaw** [comment]
Some of the smaller changes have been removed from recent release to refocus on major changes/bug fixes.
