### ISSUE TITLE
[BUG] "Save this moment!" prompt is obstructed by casual dashboard

### ISSUE THREAD

**Issue by Sloofy** [CriticalFlaw/TF2HUD.Fixes#63]
**Issue**
When you die, the pop up to screenshot the killcam has its icon obstructed by the casual dashboard. This would need to be lowered to accommodate it.

**Steps to Reproduce**
1. Join a match.
2. Die from a player to initiate the killcam screen.
3. Observe results.

**Specifications**
Latest Community branch as of April 24th, 2022
Fedora Linux KDE 35
English-CA
1920x1080

**Screenshots**
![screenie4](https://user-images.githubusercontent.com/18003771/164990103-bb95b9fd-05f0-4559-a1da-3c4835a7eae7.png)

**Comment by Sloofy** [comment]
Should note that if the server has replays enabled, a second prompt will appear underneath this one asking to create a replay. Both should be accommodated for by moving them down if this change is made. Here's a screenshot of how it looks in the default TF2 hud, courtesy of Soviet Womble's stream.
![Screenshot_20220424_110603](https://user-images.githubusercontent.com/18003771/164990281-c62b3de1-383e-4249-b9e3-13abfb2f55ac.png)

**Comment by CriticalFlaw** [comment]
> @CriticalFlaw Can you add this fix to the main branch? Right now it's only in the .extras folder

yes
