### ISSUE TITLE
[BUG] The match HUD of the Workshop Pack is the same as the Complete Pack

### ISSUE THREAD

**Issue by ArmorKeik** [CriticalFlaw/TF2HUD.Fixes#66]
**Issue**

I was told a long time ago that the Workshop Pack is only in charge of correcting bugs in the default HUD but maintaining its original aesthetic.

But in the 63aa56995e83c9f3dea552189e47df2372b243c4 update they re-added the hudmatchstatus.res file that the 2fdc36a611d33fc2114ed642d94bb54fbaa9823a update had removed.

But this hudmatchstatus.res has the same aesthetic as the one in the Complete Pack. I don't know if this is a bug or a change they made on purpose, but just in case, I'll report it. _(I use a translator, so I hope everything was understood well)._

**Specifications**

PACK: Workshop.
Operating system: Windows 10 21H1.
Language: Spanish (Spain).
Screen resolution: 1360x768.

**Screenshots**

![The Workshop Pack with the hudmatchstatus res file](https://user-images.githubusercontent.com/87909542/177016817-10994945-edea-4dd7-be58-243c78aa68be.jpg)
![The Workshop Pack without the hudmatchstatus res file](https://user-images.githubusercontent.com/87909542/177016818-89a9f1b8-0c82-4552-a984-111d5e1973d8.jpg)
![The default HUD of the game](https://user-images.githubusercontent.com/87909542/177016821-1fa43138-0131-4543-b91c-1a9883558b40.jpg)

**Comment by CriticalFlaw** [comment]
This is intentional because the background element causes overlaps with other elements, such as in spectator where if you have match HUD enabled the background element will not disappear and instead overlap the player panels. It's better off without it.

**Comment by ArmorKeik** [comment]
I see, so I'll play without the hudmatchstatus.res because I like the default better.

If I delete this file I don't miss many corrections, do I?

**Comment by CriticalFlaw** [comment]
You'll be fine, I think
