### ISSUE TITLE
[QUESTION] Thematic font used in the Workshop Pack.

### ISSUE THREAD

**Issue by ArmorKeik** [CriticalFlaw/TF2HUD.Fixes#68]
**Issue**
This engineer panel changed its font to a larger, more readable font, but the question is was it intentional to bring this change to the Workshop Pack?

**Specifications**
Pack: Workshop.
Operating system: Windows 10 Pro (21H2).
Language: Spanish (Spain).
Screen resolution: 1360x768.

**Screenshots**

DEFAULT:
![Engineer's building panels (Default HUD)](https://user-images.githubusercontent.com/87909542/177832794-082cfe57-0955-40fb-b3ac-39e9cd8e27d6.png)

WORKSHOP PACK:
![Engineer's building panels (Workshop Pack)](https://user-images.githubusercontent.com/87909542/177832824-ca54ca10-a40c-4ba4-b3e9-0bf954b3ac8a.png)

**Comment by CriticalFlaw** [comment]
This was unintentional, but it does fit in with the rest of the HUD. Not sure if the preference is to revert or keep this change.

**Comment by ArmorKeik** [comment]
> This was unintentional, but it does fit in with the rest of the HUD. Not sure if the preference is to revert or keep this change.

And, the thematic font is more legible because the original one is very small (although this never mattered because when you see the color of the panel and the drawings you can understand it).

But I don't know if Valve will accept the Workshop HUD if it changes too much from the original.
_I guess the change will have to be reverted._

**Comment by CriticalFlaw** [comment]
Valve can choose to simply not include those files since the only thing they change is the font afaik. The whole workshop pack is submitted in such a way that they can choose what to include a la carte.

**Comment by ArmorKeik** [comment]
I forgot to ask you.
How do I revert this change, do I have to delete a whole file as I did before with the _hudmatchstatus.res_ or just editing one file is enough?
