### ISSUE TITLE
Player list is not properly aligned in MVM

### ISSUE THREAD

**Issue by objectionist** [CriticalFlaw/TF2HUD.Fixes#69]
**Issue**
The player list seen at the top of the screenshot seems to create a weird staircase effect when spectating in MVM.

**Specifications**
Playing on Windows 10, using the Community branch and in 1080p. This bug occurs frequently when dying, while spectating and waiting to respawn in MVM.

**Screenshots**
![20220707092446_1](https://user-images.githubusercontent.com/86072496/177881373-e87c718b-219d-461c-8e0d-28656c300011.jpg)

**Comment by CriticalFlaw** [comment]
From my testing it looks to be a game bug that's fixed by entering `hud_reloadscheme` into console once.

**Comment by CriticalFlaw** [comment]
Closing per earlier comment where it was found that this is a game bug corrected by using `hud_reloadscheme`.
