### ISSUE TITLE
Match HUD timer and Setup label are out of position

### ISSUE THREAD

**Issue by Sterling1245** [CriticalFlaw/TF2HUD.Fixes#70]
**Issue**
Joining a match for the first time while using `tf_use_match_hud 0` has the timer panel off position. This can be fixed by toggling it to 1 and then back to 0. The setup label is also off with both 1 and 0. I am not sure if it is an issue with this hud or a game issue.

**Specifications**
Branch: community, workshop
OS: Windows 10
Resolution: 1920x1080

**Screenshots**
Joining a match for the first time:
![matchhud1](https://user-images.githubusercontent.com/106461801/178102543-a27c49ef-eb7e-4cd7-8aa6-3b36fbf3032a.png)

After toggling from 1 back to 0:
![matchhud2](https://user-images.githubusercontent.com/106461801/178102556-186c5da5-356a-4768-89b3-a0170e5e7fa9.png)

Setup label off position after setting back to 1 from previous toggle:
![matchhud3](https://user-images.githubusercontent.com/106461801/178102576-0b34b90d-c034-4025-b9a4-e8f7d3c64d16.png)

**Comment by CriticalFlaw** [comment]
I was able to reproduce it but it fixed itself when entering `hud_reloadscheme` into console once. Could you please verify?

**Comment by Sterling1245** [comment]
> I was able to reproduce it but it fixed itself when entering `hud_reloadscheme` into console once. Could you please verify?

Yes, that fixes it as well but we should not need to do this in the first place.

**Comment by CriticalFlaw** [comment]
I agree but this doesn't happen because it's set incorrectly in the hud files afaik. It'd have to be fixed in the game code.

**Comment by Sterling1245** [comment]
> I agree but this doesn't happen because it's set incorrectly in the hud files afaik. It'd have to be fixed in the game code.

When I made this post I did not test it with the default hud, so my mistake.
