### ISSUE TITLE
Change ammo icon on the TargetID from "leaderboard_class_heavy" to "hud_obj_status_ammo_64"

### ISSUE THREAD

**Issue by Ashetf2** [CriticalFlaw/TF2HUD.Fixes#71]
**Is your feature request related to a problem? Please describe.**
The vanilla texture used for ammo in the target display can be confusing, because it can give the impression of healing a Heavy. I suggest to change the Heavy icon to the one used for ammo crates
![image](https://user-images.githubusercontent.com/63692647/178799489-deabac09-587f-4e61-8734-77e15560843c.png)

**Additional context**
Only for complete pack i guess

**Comment by CriticalFlaw** [comment]
Added in e320c85325ef607b9638eaa6af806d71b3e135da
