### ISSUE TITLE
[BUG] MVM respawn label visual glitch

### ISSUE THREAD

**Issue by Maurvick** [CriticalFlaw/TF2HUD.Fixes#74]
**Issue**
Broken spectator

**Specifications**
Additional information about the issue. Branch: Workshop, Windows 11, English, 16:9 and press kill bind when playing mvm. 

**Screenshots**
![20220725214304_1](https://user-images.githubusercontent.com/82706197/180860114-aae4a968-f62b-4a41-a7c9-021d978527c5.jpg)

**Comment by SharpForms** [comment]
spectatortournament.res cause this bug

**Comment by CriticalFlaw** [comment]
Fixed in 98e2b470d62bdc2cb26edb8112ff52dab703d1a5. Thanks!
