### ISSUE TITLE
[BUG] Unable to view entire numbers when healing certain classes

### ISSUE THREAD

**Issue by yslupdates** [CriticalFlaw/TF2HUD.Fixes#75]
**Issue**
Often when I overheal a soldier, their health text (in the pop up box when I'm healing them) shows as an abbreviated number like "30..." instead of being "300". I think this happens with large numbers and the space where the text goes has too small of a box?

**Specifications**
2560x1440 resolution
12600k/3070
Installed TF2HUD fixes via the TF2 HUD Editor app.

**Screenshots**
![20220724213355_1](https://user-images.githubusercontent.com/53108354/181711423-7db26ceb-841d-44b4-b4aa-4e320903d8c5.jpg)
![20220724221958_1](https://user-images.githubusercontent.com/53108354/181711429-43c7608a-08d2-41e7-8f23-e51e5b7c43ca.jpg)
![20220724213409_1](https://user-images.githubusercontent.com/53108354/181711433-fb651356-47aa-4cc9-981f-c7c40cba68cd.jpg)

**Comment by CriticalFlaw** [comment]
Fixed in b0e6cde275cec70ab89adb9d73af348d0afcfb11. Thank you for reporting the issue.
![image](https://user-images.githubusercontent.com/6818236/181871707-3ad511a3-9304-4df7-bc20-d0135ad1f0cc.png)

**Comment by yslupdates** [comment]
Thanks a lot!
