### ISSUE TITLE
[BUG] Pomsom meter is misplaced

### ISSUE THREAD

**Issue by Ashetf2** [CriticalFlaw/TF2HUD.Fixes#77]
**Issue**
Title.

**Specifications**
Nothing

**Screenshots**
Vanilla
![image](https://user-images.githubusercontent.com/63692647/182042668-1488d522-0ad1-4906-8710-0415fbe940df.png)
HUD fixes
![image](https://user-images.githubusercontent.com/63692647/182042677-9808b7d2-2b68-4d85-9452-cd8c31473801.png)

**Comment by CriticalFlaw** [comment]
Are you using the latest version off GitHub and do you have the file `resource/ui/huditemeffect_pomson.res`?

**Comment by Ashetf2** [comment]
Yes and yes

**Comment by CriticalFlaw** [comment]
odd, it doesn't have this issue in the latest Github version. What's the map and weapons you have equipped when this occurs?

**Comment by Ashetf2** [comment]
It happens in all maps, Pomson + Pistol + Jag.

**Comment by Ashetf2** [comment]
So, any clue why this is happening?

**Comment by CriticalFlaw** [comment]
For some reason the `x_offset` value is only used when you have the Lugermorph equipped which is what I used during my testing. That's why this wasn't caught earlier. It's been fixed now. Cheers.
