### ISSUE TITLE
[BUG] In min mode freeze panel does not show min mode health like on targetid

### ISSUE THREAD

**Issue by Maurvick** [CriticalFlaw/TF2HUD.Fixes#79]
**Issue**
Wrong health icon on freeze panel

**Specifications**
Workshop,
Win11
English
16:9

**Screenshots**
![Знімок екрана 2022-08-03 164322](https://user-images.githubusercontent.com/82706197/182638042-2ecbfd6a-de61-4813-9f88-b63cd566614e.png)
![20220803174506_1](https://user-images.githubusercontent.com/82706197/182638137-609b6cea-1494-4c03-a639-e29af095fc73.jpg)

**Comment by CriticalFlaw** [comment]
I'm not sure I see the difference. It's the same health cross and value but smaller on the TargetID compared to the killfeed. Making the latter small to match would just make it too hard to see.

**Comment by Maurvick** [comment]
It's just add consistency to default hud

**Comment by CriticalFlaw** [comment]
I've tried to add your suggestion by adding "_minmode" values to `freezepanel_basic.res` and freezepanelkillerhealth.res` - however the end result is admittedly pretty bad. You can hardly see the health value when on minmode so I don't know if this is something that's worth adding.

If you want to try it for yourself add the below files, just change the extension from .txt to .res
[freezepanel_basic.txt](https://github.com/CriticalFlaw/TF2HUD.Fixes/files/9305484/freezepanel_basic.txt)
[freezepanelkillerhealth.txt](https://github.com/CriticalFlaw/TF2HUD.Fixes/files/9305486/freezepanelkillerhealth.txt)

![20220810215718_1](https://user-images.githubusercontent.com/6818236/184052620-2c24e5d6-0915-401d-b29d-9af369ae193a.jpg)

**Comment by Maurvick** [comment]
I see, then it is better to leave everything as it is. Thank you for checking this out.
