### ISSUE TITLE
[REQUEST] Option/way to remove the bottom bar when spectating 

### ISSUE THREAD

**Issue by As0mn** [CriticalFlaw/TF2HUD.Fixes#82]
**Is your feature request related to a problem? Please describe.**

*This isn't really a request, but this doesn't fall into the bug category either*

Hi, I really like this hud and appreciate the work on it, however I would like to know how to completely remove the bottom bar when spectating. I know it is semi-transparent but I would still like it gone completely. If you could let me know how to remove it that would be much appreciated  

**Additional context**
Screenshot of the bottom bar
![image](https://user-images.githubusercontent.com/109611240/184499096-ce073522-49f4-4a97-81de-73b7fc080313.png)

**Comment by CriticalFlaw** [comment]
Hi. This counts as more of a question than a request or bug report. To remove or change the color of that bar you'll need to go to `tf/custom/tf2hud.fixes/resource/ui/spectator.res` and under **HeaderBG** change the value of visible and enabled from 1 to 0.

Alternatively you can change the value of bgcolor_override to another RGBA value like "0 0 0 0" which would make that panel invisible.

![image](https://user-images.githubusercontent.com/6818236/184503081-694126af-b1cb-4904-ac3a-15b21fa7fdc0.png)

**Comment by As0mn** [comment]
This removed the bar, thank you! 
Also sorry for not making it a question, I didn't know that was an option.

**Comment by CriticalFlaw** [comment]
All good, enjoy!
