### ISSUE TITLE
[REQUEST] Add Fixed 16:9 Loading Screen mod to TF2 HUD Fixes

### ISSUE THREAD

**Issue by ArmorKeik** [CriticalFlaw/TF2HUD.Fixes#83]
**Is your feature request related to a problem? Please describe.**
I suggest you add [this mod](https://gamebanana.com/mods/397571) to TF2 HUD Fixes.
This fix fixes the bug where the loading screen looks too stretched and cropped (the Medic's head is cropped by default).

**Additional context**
I already tried this mod with the TF2 Hud Fixes version from the Workshop and everything went well.
In addition to the fact that the mod corrects the position of the image, it improves its quality, making it look much better.

![imagen_2022-08-22_225013776](https://user-images.githubusercontent.com/87909542/186050837-bdef34b4-4a7c-4dbc-89e5-fc2a9f5bd813.png)

![imagen_2022-08-22_225037988](https://user-images.githubusercontent.com/87909542/186050889-7e6152a6-2cd9-49d4-a471-e398529d47d8.png)

**Comment by Maurvick** [comment]
#86

**Comment by CriticalFlaw** [comment]
Added in https://github.com/CriticalFlaw/TF2HUD.Fixes/pull/86 by @Maurvick
