### ISSUE TITLE
[BUG] Player Destruction objective tracker is misplaced

### ISSUE THREAD

**Issue by Maurvick** [CriticalFlaw/TF2HUD.Fixes#84]
**Issue**
This happens when min mode is on and after someone score points. hud_reloadsheme fixes objective panel, but after someone score points, it breaks again.

**Specifications**
Windows 10
English
Workshop

**Screenshots**
![20221014123700_1](https://user-images.githubusercontent.com/82706197/195816976-1fc3c864-4200-41ae-8d69-4d5d19514286.jpg)

**Comment by CriticalFlaw** [comment]
I suspect that when the numbers "jump" they revert to their default position which may be a code-side setting and not something that can be changed in the HUD files. I'll ask the other developers who have worked on this UI element to see if they have a solution.

**Comment by CriticalFlaw** [comment]
Fixed in 7f53dc8fb8d4ccca87e8d2b24bee261974806fee. Thank you for reporting.
