### ISSUE TITLE
[BUG] Item meters using #base are not vertically aligned

### ISSUE THREAD

**Issue by Maurvick** [CriticalFlaw/TF2HUD.Fixes#85]
**Issue**
tf2hud.fixes meterers are displayed lower than on the default hud, demoman pipes are misaligned in min mode, sniper have 2 meter bars for huntsman

**Specifications**
16:9, Workshop, W10, English

**Screenshots**

---TF2HUD.FIXES---
![20221025144908_1](https://user-images.githubusercontent.com/82706197/197765826-5a83b9ce-bd39-49a4-8e63-0fe785d67bc3.jpg)
![20221025114147_1](https://user-images.githubusercontent.com/82706197/197772633-fb137875-9015-42e8-a4f1-fc515b868fa9.jpg)
![20221024132136_1](https://user-images.githubusercontent.com/82706197/197506186-cd836c45-2bb2-4985-b45e-b902d621a6f4.jpg)
![20221024132147_1](https://user-images.githubusercontent.com/82706197/197506193-3d75309d-42a9-4d41-b2b3-2697851e6ce7.jpg)
![20221024132215_1](https://user-images.githubusercontent.com/82706197/197506195-3250b9ae-2ead-452d-a08d-94f99239d2e1.jpg)
![20221024132232_1](https://user-images.githubusercontent.com/82706197/197506201-30168d06-5586-4ef7-906e-fc1d4620e591.jpg)
![20221024132241_1](https://user-images.githubusercontent.com/82706197/197506203-1e4ff287-0736-4194-b9d0-f8a6a07dc941.jpg)
![20221024132256_1](https://user-images.githubusercontent.com/82706197/197506208-7db8f2c5-5ac0-4ac0-983f-32f319dc0916.jpg)
![20221024132300_1](https://user-images.githubusercontent.com/82706197/197506210-5e41bb66-b128-43eb-8a94-706cef007692.jpg)

---DEFAULT---
![20221024133154_1](https://user-images.githubusercontent.com/82706197/197506855-9250d0a9-2f29-4416-9d62-cd81cef28e39.jpg)
![20221024133114_1](https://user-images.githubusercontent.com/82706197/197506859-564643c9-c5b8-4516-8f6b-ce1e0110a364.jpg)
![20221024133116_1](https://user-images.githubusercontent.com/82706197/197506864-d4c2cefd-0f88-46fa-8830-5a920966baaf.jpg)
![20221024133134_1](https://user-images.githubusercontent.com/82706197/197506865-8d8ff79e-b446-40fb-a7c7-48c32c7fca60.jpg)
![20221024133145_1](https://user-images.githubusercontent.com/82706197/197506867-cf2233d1-8bde-4812-9f5b-a7f69678bdce.jpg)
![20221024133152_1](https://user-images.githubusercontent.com/82706197/197506874-df5c0da4-1475-4c52-9b07-c12a979fd0bf.jpg)

**Comment by Maurvick** [comment]
I managed to fix scout meter by adding xpos for huditemeffectmeter_cleaver.res, but other is still bugged.
![20221025103533_1](https://user-images.githubusercontent.com/82706197/197715304-00e0ae46-adf5-4d7e-9f9d-26433bf72364.jpg)

**Comment by Maurvick** [comment]
#87

**Comment by CriticalFlaw** [comment]
Is the position fixed in 4:3, 16:9 and 16:10 resolutions? afaik some elements shift in different resolutions.

**Comment by Maurvick** [comment]
i tested it only on 16:9

**Comment by CriticalFlaw** [comment]
Please check the PR in other aspect ratios to make sure the position is still correct. If it's good then it can be added in.

**Comment by Maurvick** [comment]
#87
