### ISSUE TITLE
[BUG] demoman pipes are misaligned in min mode

### ISSUE THREAD

**Issue by Maurvick** [CriticalFlaw/TF2HUD.Fixes#89]
**Issue**
A clear and concise description of what the issue is.

**Specifications**
16:9, Workshop, W10, English

**Screenshots**
![20221024132136_1](https://user-images.githubusercontent.com/82706197/197868587-de6d8597-8778-4348-be7e-ab840134c74b.jpg)

**Comment by CriticalFlaw** [comment]
Fixed in 9f341ecfcb83b06775f14ee12eabe13e1caf16c0. Thank you for reporting the issue.
