### ISSUE TITLE
[BUG] Sniper has 2 meter bars for huntsman in min mode

### ISSUE THREAD

**Issue by Maurvick** [CriticalFlaw/TF2HUD.Fixes#90]
**Issue**
2 effect meters 1 weapon

**Specifications**
Workshop, 16:9, English, W10

**Screenshots**
![20221025144908_1](https://user-images.githubusercontent.com/82706197/197869050-ba7aea71-e875-420f-8607-47d62077de93.jpg)

**Comment by CriticalFlaw** [comment]
Fixed in 9f341ecfcb83b06775f14ee12eabe13e1caf16c0. Thank you for reporting the issue.
