### ISSUE TITLE
[REQUEST] Update Consistent and Missing Kill Icons mod

### ISSUE THREAD

**Issue by ArmorKeik** [CriticalFlaw/TF2HUD.Fixes#91]
**Is your feature request related to a problem? Please describe.**
They have created a new version of the mod created by Hootaro_Hoestar, [Consistent and Missing Kill Icons](https://gamebanana.com/mods/25953) which I suggested in [this comment](https://github.com/CriticalFlaw/TF2HUD.Fixes/issues/23#issuecomment-980276682).

The new version, created by SiFWolf, is called [Better Consistent and Missing Kill Icons (2022)](https://gamebanana.com/mods/406361).

**Additional context**
As the new author indicates in [this post](https://gamebanana.com/mods/25953?post=10325357), he had to create a new version because the one I suggested to you before is currently obsolete.

I haven't tested this mod with TF2HUDFixes, but I doubt there will be any conflict.

![image](https://user-images.githubusercontent.com/87909542/198139667-feb5fc1c-f5ff-437b-ac2f-f4f23c933965.png)

![image](https://user-images.githubusercontent.com/87909542/198139697-97302386-91d0-4ee7-8fde-59fe629e15ec.png)

**Comment by Maurvick** [comment]
#92

**Comment by CriticalFlaw** [comment]
We would need the creator's permission to add this mod to this repo.

**Comment by ArmorKeik** [comment]
> We would need the creator's permission before adding this mod to the repo.

The creator [gave you his permission](https://gamebanana.com/mods/406361?post=10360435).

**Comment by CriticalFlaw** [comment]
Implemented in https://github.com/CriticalFlaw/TF2HUD.Fixes/pull/92 by @ArmorKeik with creator's approval.
