### ISSUE TITLE
[REQUEST] Add a button to open the console to the main menu

### ISSUE THREAD

**Issue by Ashetf2** [CriticalFlaw/TF2HUD.Fixes#94]
**Is your feature request related to a problem? Please describe.**
Since users can't open the console from the main menu once close, it would be nice to have one extra button to do it.

**Additional context**
To the Community pack.

**Comment by CriticalFlaw** [comment]
Added in d8e05b508969a28f3b45e80507a3a44bc0c7a77b. The icon used will likely be revised in the future.

![image](https://user-images.githubusercontent.com/6818236/198852298-627a8970-6267-402e-8bad-17f622a7860c.png)

**Comment by kittenchilly** [comment]
It is worth noting that you actually can open the console once closed, with the ~ button.
