### ISSUE TITLE
[BUG] Bumper car damage percentage is misplaced

### ISSUE THREAD

**Issue by Ashetf2** [CriticalFlaw/TF2HUD.Fixes#95]
**Issue**
Title

**Specifications**
- Res: 1920x1080
- Windows
- Community

**Screenshots**
Vanilla

![hl2_2nLxOVomSx](https://user-images.githubusercontent.com/63692647/198864564-3ba35a88-f44e-411d-b14e-bf6471e67fa5.png)

Mod

![hl2_85JZFCdHu4](https://user-images.githubusercontent.com/63692647/198864576-889a98cb-7c37-43d9-9ee0-bfb4a08af676.png)

**Comment by CriticalFlaw** [comment]
Fixed in 4101c62088bb7657aacc0e57d6d61e5c64d0d5e9. I've noticed that sometimes it may not show everything so try do a `hud_reloadscheme` to correct that. Thanks.

![20221105201929_1](https://user-images.githubusercontent.com/6818236/200148309-3d5c64c7-0ab7-4c22-ac04-c69488801792.jpg)
