### ISSUE TITLE
[BUG] MVM Misplaced respawn UI

### ISSUE THREAD

**Issue by ThatGreenBlur** [CriticalFlaw/TF2HUD.Fixes#96]
**Issue**
In MVM the "Respawn In:" text and "Wave" label is misplaced, also the engineer building ui overlaps with the player list

**Specifications**
Community
Windows 11
English
1920x1080
die on mvm mid wave

**Screenshots**
![20221031120000_1](https://user-images.githubusercontent.com/115673550/199057008-7b80a8ab-62e7-4e05-9290-4218ba6e9d1a.jpg)

**Comment by CriticalFlaw** [comment]
I'm not seeing this on my side with the latest version. Does this happen on non-custom servers?\

![20221105180312_1](https://user-images.githubusercontent.com/6818236/200143070-8da8916c-b0b6-4a62-89be-629392c1d5af.jpg)

**Comment by ThatGreenBlur** [comment]
yes, i remember it happening on boot camp

**Comment by CriticalFlaw** [comment]
Is it fixed with `hud_reloadscheme`?

**Comment by ThatGreenBlur** [comment]
just joined bootcamp 
![20221106091532_1](https://user-images.githubusercontent.com/115673550/200149503-8d770cd7-0da7-4a7b-8267-23affcae8c35.jpg)

**Comment by ThatGreenBlur** [comment]
btw watch out for the engineer building screen overlapping with the player list

**Comment by ThatGreenBlur** [comment]
hud_reloadscheme does fix my issue

**Comment by CriticalFlaw** [comment]
Could you please redownload the latest version from here and retest: https://github.com/CriticalFlaw/TF2HUD.Fixes/archive/refs/heads/community.zip

https://github.com/CriticalFlaw/TF2HUD.Fixes/commit/ff03938736d02f3de5914e0947906b8e040a54d9

**Comment by ThatGreenBlur** [comment]
retested with the latest version, not fixed
![20221109152811_1](https://user-images.githubusercontent.com/115673550/200766284-3ddc1568-be40-4f9f-9959-8eec72af0566.jpg)

**Comment by ThatGreenBlur** [comment]
oops, im so sorry, idk why it says windows 10 but im actually using windows 11

**Comment by CriticalFlaw** [comment]
Try it once more please. I've aligned the text to the right corner since the if_mvm values are not being respected.

**Comment by ThatGreenBlur** [comment]
the text is now properly aligned to the right corner but the wave thing still goes down

**Comment by CriticalFlaw** [comment]
That's hard-coded I believe, but I'll check

**Comment by CriticalFlaw** [comment]
Yup it's hardcoded. Closing.
