### ISSUE TITLE
[BUG] Report/Call Vote button group broken

### ISSUE THREAD

**Issue by hkva** [CriticalFlaw/TF2HUD.Fixes#97]
**Issue**
The four buttons in the bottom-center of the screen for reporting/kicking/muting/coaching players all have medic icons and do nothing when clicked.

**Specifications**
This happens on any commit on the community branch after d8e05b508969a28f3b45e80507a3a44bc0c7a77b
I am using the latest version of TF2 (7638371) on Linux at 1920x1080

**Screenshots**
![2022-11-05-033144_1920x1080_scrot](https://user-images.githubusercontent.com/91440203/200111109-1ca8c953-ba8d-4309-bfd1-206933d78ff9.png)
![2022-11-05-033224_1920x1080_scrot](https://user-images.githubusercontent.com/91440203/200111111-e43a5943-5583-4ca6-b918-2767b6691374.png)

**Comment by CriticalFlaw** [comment]
I'm not seeing the same issue on Windows 11 at 1920x1080. Does this happen with a clean install from GitHub or the editor?

![20221105112213_1](https://user-images.githubusercontent.com/6818236/200127150-1364788a-5add-43ce-a7eb-23c8d8b48228.jpg)

**Comment by hkva** [comment]
Fixed with #98

**Comment by CriticalFlaw** [comment]
Not sure I understand how that fixed your problem but whatever works.
